### ISSUE TITLE
Create Connectivity Plugin

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#115]
The connectivity plugin will handle connectivity logic. The logic will be triggered on Connectors Updated event.

Detalied description of the plugin's logic can be found here - 
http://qs-srv-confluence:8090/display/QP/L2+Connectivity+and+VLAN+Improvements+-+Design

flow 1 - connect
============
the flow for connect will be: (0) validate that the VLAN ID input (if non empty) fits the allocation ranges (1) a connect command is called (2) it sends a GetItemFromPool request (3) it gets the selected VLAN ID (specific/range) as a result and put it on the "Virtual Network" attribute (4) it updates the alias on the connector (different story)

if user input in "VLAN ID" is a specific number:
GetItemFromPool([PoolID=domainName], [reservationId], [Selection_Criterion=Criterion.NextUnusedNumeric(Vlan_ID)], [Isolation_Level])

if user input in "VLAN ID" is a range:
GetItemFromPool([PoolID=domainName], [reservationId], [Selection_Criterion=SpecificRanges(VLAN_ID)], [Isolation_Level])

*note: in case the "Virtual Network" attribute has a value than steps 2 and 3 in the flow above shouldn't happen

flow 2 - disconnect
==============
the flow for disconnect will be: (1) a disconnect command is called (2) the "Virtual Network" attribute value is kept on the VLAN (3) updates the alias on the connector (different story)

note - the item isn't released from the pool in this case

flow 3 - service removal
==================
once this service  is removed from the reservation  the flow will be: (1) check if there is a value in the "Virtual Network" attribute, if so (2) call ReleaseItemFromPool for the ID/range according to the value in the Virtual Network attribute and the ID of the service itself

Implementation Notes
=================
GetItemFromPool

   - PoolId - String index, this identifies the virtual pool
   - Selection criterion:
        - Auto select 
        	- SelectFirstAvailableNumeric (10-100)
        	*(for later) - SelectFirstAvailableRange (rangelength, 10-10000)
        - Manual select
            - SpecificNumeric -  I know what I want - Specific number or range
            - SpecificNumericRange -  I know what I want - Specific number or range

ReleaseItemFromPool(reservationId,SpecificNumeric/SpecificNumericRange)

SpecificNumeric/Range inherits from SpecificItem
 - Validate Isolation
     1. Checks if item already exists in pool (for that key)
     2. Allow shared(existing)/shared(new) , Do not allow shared(existing)/exclusive(new) or exclusive(existing)/shared(new) or exclusive(existing)/exclusive(new)

 Select first avilable numeric:
   - Goes through provided range 
   - For each range item check the 'SpecificItem' validation
   - Return first that returns true  

Implementation notes:
   - Should be atomic operation to check if available and 'checkout' item (we need to support this with concurrency)

 PoolKey  | Item (string) | Reservation Id | Isolation
   Global |            2  |     Id         | Exclusive

Add hook to reservationended event:
   - Register to domain even, on reservation ended always remove all of the reservation items

**Comment by alexazarh** [comment]
Flow 1 & 2 & 3 are implemented and checked-in to trunk :)

**Comment by alexazarh** [comment]
@nahumtimerman fixed bug on disconnecting in p2p scenario
