### ISSUE TITLE
Support PortGroup security policy definition

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#123]
Support working in promiscuous mode when configuring port group in the vCenter (promiscuous is the flag to indicate whether or not all traffic is seen on the port).

Add an attribute to the vCenter that defines the security policy. The admin will define on the vCenter the default (Promiscuous Mode = True / False) and the Connect command should work accordingly.

**Comment by doppleware** [comment]
For now we should only support a default of permiscuous = true

**Comment by alonagetzler** [comment]
Let's juts check that the default port group security policy is defined as promiscuous=accept and remove the attribute

**Comment by razaba** [comment]
we decided to remove promiscuous mode
