### ISSUE TITLE
Visual connector gets the VM deployment app name

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#141]
STR:
1) add deployment app and connect it to a vlan
2) deploy the app

result:
the visual connector alias is updated with the app deployment name

expected behavior:
visual connector should remain without alias

**Comment by doppleware** [comment]
Should be fixed with #115

**Comment by doppleware** [comment]
Long done

**Comment by TomerAdmon** [comment]
fixed
