### ISSUE TITLE
vCenter cross versions compatability

### ISSUE THREAD

**Issue by borismod** [QualiSystems/vCenterShell#146]
As a user I would like vCenterShell to work seamlessly with different versions of vCenter: 5.0, 5.5. and 6.0

There might be a difference in port group creation API:

try:
    # vCenter 6.0
    task = dvswitch.CreateDVPortgroup_Task(spec=spec)
    self.wait_task(task, progress_handler=progress_handler)
    return typedmoref(task.info.result)
except vmodl.fault.MethodNotFound:
    # vCenter 5.0
    task = dvswitch.AddDVPortgroup_Task([spec])
    self.wait_task(task, progress_handler=progress_handler)
    pgobj = self.get_portgroup_by_name(name)
    return pgobj.moref

**Comment by alexazarh** [comment]
Is this fixed already or its still open?

**Comment by alonagetzler** [comment]
@alexazarh what's the status of that? we're supposed to be supporting vCenter 5.5 and 6.0
