### ISSUE TITLE
Create deployment service that interacts with the app orchestrator

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#15]
Create a service called "vCenter VM Template" that has a command (script) called "Deploy" which deploys a VM from a selected template. The interface of this command should be aligned with the App Orchestration flow.
Input - app deployment parameters
Output - hosted-on information to be used by the app orchestration (that builds the hotsed-on entity) - host name (=vCenter name), VM identifier (=UUID of VM), list of NICs, location (=path)

the deployment service should have the following attribute:
full path of the template (includes the name of the vCenter)

See the referenced link:
http://qs-srv-confluence:8090/pages/viewpage.action?pageId=4856595

**Comment by alexazarh** [comment]
I'm  waiting for the python driver to be ready. Until then I can't start working on this story.

**Comment by alexazarh** [comment]
It works under apps and currently the information that the deployment service returns is: 
1) VM Name,
2) UUID
3) vCetner Inventory Path (vCenter resource name + VM location)
 
list of NICs is also required (just to verify)?
