### ISSUE TITLE
Default folder (cloudshell) in which the deployed app resource will be created

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#151]
All the the VM (deployed app) resources should be created under a folder named "[vCenterName] VMs", and not under the root folder. Each vCenter will have its own folder.

**Comment by alonagetzler** [comment]
apparently that's something in the DeployApp server method and not on our end.

**Comment by alexazarh** [comment]
@alonagetzler - can we fix this as part of the quality spike?

**Comment by TomerAdmon** [comment]
Proposal: Create apps under a folder with the cloud provider name.
Shay & Ariel will discuss.
