### ISSUE TITLE
Advanced refresh IP

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#152]
Some enhancements:
Should wait for IPv4 only 
Refer to an optional 'IP Regex' attribute to only wait for an IP of a specific network etc. (that way we get around the changing networking bugs)
Avoid checking if VM isn't powered on for some reason.

**Comment by borismod** [comment]
@doppleware "IP Regex" should be on what resource?

**Comment by alonagetzler** [comment]
delta - (1) update IP regex on deployed app (2) add support for cancellation token (3) validate that VM tools are installed and throw good error if not

**Comment by borismod** [comment]
1) Update IP Regex on deployed app - DONE
2) add support for cancellation token  - GAP
3) Validate that VMWare Tools are installed and running and throw comprehensive error - DONE
