### ISSUE TITLE
OOB setup and teardown orchestration

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#153]
Create an out of the box setup/teardown scripts that implement a 'sandbox' behavior for environments.

http://conf:8090/pages/viewpage.action?pageId=7144703

The names of the Setup and Teardown scripts should be "CloudShell Sandbox Setup" and "CloudShell Sandbox Teardown" respectively.

Setup:
1.  Call 'DeployAppResources' as one bulk command for all resources in the reservation
2. Call connectRoutes in the reservation sending all of the reservation routes 
3.  On all deployed app resources, call 'power on' and 'refresh IP' (in parallel)
4. On all deployed app resource call Install

Teardown:
Call disconnectRoutesInReservation sending all of the reservation connected routes
 Call 'Power off'  on all vm resources in the reservation

Dev note:
connectRoutesInReservation
-> if visual connector is not connectable  than throw exception: The following "visual connectors"/connector doesn't support this action: a<->b"
-> if there are both connectable connector and a route between the same endpoints, throw error: "Found two contradicting connections between <A> and <B>"

disconnectRoutesInReservation
-> if visual connector is not connectable  than throw exception: The following "visual connectors"/connector doesn't support this action: a<->b"
-> -> if there are both connectable connector and a route between the same endpoints, throw error: "Found two contradicting connections between <A> and <B>"

**Comment by alexazarh** [comment]
Setup & Teardown ready.
I also had to update the API so it is required to get latest from the trunk and also make sure you are using the latest cloudshell-automation-api

**Comment by nahumtimerman** [comment]
does connectroutes trigger only for CVC or for all routes in reservation?

**Comment by alexazarh** [comment]
all routes

Best regards,
Alex Azarh

**Comment by nahumtimerman** [comment]
in the real world, what are these scripts associated with - an environment? a service?
Are they driver "setup" & "teardown" - i.e. run on start and end, or called by somebody else?

**Comment by nahumtimerman** [comment]
OK, Alex explained that these scripts are associated with topologies as setup and teardown commands
