### ISSUE TITLE
Installation service doesn't work

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#154]
currently, installation service will try to execute hardcoded a command name 'install' 
with 'STAM' parameter

Deploy App ended with status Failed with error: 01/Feb/2016 15:00:48 INFO Executing 'vCenter VM From Template' on app 'Selenium Grid'...
01/Feb/2016 15:04:15 INFO Powering on deployed app Ubuntu_3de5c7f2
01/Feb/2016 15:04:15 DEBUG Powering on deployed app Ubuntu_3de5c7f2. VM UUID: 4222823e-083e-e9be-5234-6cf35ba56ebc
01/Feb/2016 15:04:17 INFO Executing installation 'Generic Installation Option' on deployed app resource 'Ubuntu_3de5c7f2'...
01/Feb/2016 15:04:17 ERROR Error installing deployed app Ubuntu_3de5c7f2. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteInstallAppCommand" Success="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><Error>Unable to locate a valid command named 'Install'</Error><ErrorCode>101</ErrorCode></Response>

**Comment by alexazarh** [comment]
fixed

**Comment by TomerAdmon** [comment]
fixed
