### ISSUE TITLE
deploy vm - when datastore not exsists throw masive error

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#155]
STR:
1) try to deploy a VM with non exsisting datastore

Deploy App ended with status Failed with error: 01/Feb/2016 16:03:30 INFO Executing 'vCenter VM From Template' on app 'Test VM'...
01/Feb/2016 16:03:34 ERROR Error deploying app Test VM. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><ErrorCode>0</ErrorCode><ResponseInfo xsi:type="CommandExecutionFailedResultInfo" ErrorName="Script runner exited with exit code: 1" ErrorDescription="Traceback (most recent call last):&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA; exec code in run_globals&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\d8abd45e-c48b-4b95-88be-67f623f6823a\Deploy.zip\__main__.py&quot;, line 11, in &lt;module&gt;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\d8abd45e-c48b-4b95-88be-67f623f6823a\Deploy.zip\__main__.py&quot;, line 8, in main&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\d8abd45e-c48b-4b95-88be-67f623f6823a\Deploy.zip\driver.py&quot;, line 27, in execute&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py&quot;, line 5127, in ExecuteCommand&#xD;&#xA; raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;&#xA;qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.&#xD;&#xA;&#xD;&#xA;Error description: 01/Feb/2016 16:03:31 INFO action:START command_name:execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:31 INFO connecting to vcenter: 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:31 DEBUG connection params: host: 192.168.42.110 username: administrator@vsphere.local port: 443&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:32 INFO Starting new HTTPS connection (1): 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:32 DEBUG &quot;GET //sdk/vimServiceVersions.xml HTTP/1.1&quot; 200 552&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:32 INFO connected to vcenter: 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:32 INFO executing command: execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:32 DEBUG command params: 'vim.ServiceInstance:ServiceInstance',&lt;models.DeployDataHolder.DeployDataHolder object at 0x02F8CA30&gt;&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:32 INFO cloning VM...&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:33 INFO error type: vim.fault.NoDiskSpace&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:33 INFO found cause: None&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:33 ERROR error has occurred while executing command: execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:33 ERROR None&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\common\wrappers\command_wrapper.py&quot;, line 62, in execute_command_with_connection&#xD;&#xA;&#xD;&#xA; results = command(*tuple(command_args))&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 13, in execute_deploy_from_template&#xD;&#xA;&#xD;&#xA; deploy_result = self.deployer.deploy_from_template(si, deployment_params)&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\vCenterShell\vm\deploy.py&quot;, line 22, in deploy_from_template&#xD;&#xA;&#xD;&#xA; clone_vm_result = self.pv_service.clone_vm(params)&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 399, in clone_vm&#xD;&#xA;&#xD;&#xA; vm = self.wait_for_task(task)&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 287, in wait_for_task&#xD;&#xA;&#xD;&#xA; raise Exception(task.info.error.faultCause)&#xD;&#xA;&#xD;&#xA;Exception: None&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:33 INFO disconnecting from vcenter: 192.168.42.110&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:03:33 INFO action:END command_name:execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA;&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA;&#xD;&#xA; exec code in run_globals&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\__main__.py&quot;, line 56, in &lt;module&gt;&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\__main__.py&quot;, line 40, in main&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\vCenterShell\command_executer.py&quot;, line 209, in deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\common\wrappers\command_wrapper.py&quot;, line 62, in execute_command_with_connection&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 13, in execute_deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\vCenterShell\vm\deploy.py&quot;, line 22, in deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 399, in clone_vm&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\dfaed42f-eb15-4892-8905-b94bcbf1c49d\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 287, in wait_for_task&#xD;&#xA;&#xD;&#xA;Exception: None&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;"><ErrorParameters/></ResponseInfo></Response>

**Comment by doppleware** [comment]
Less urgent because of autoloa dvalidation
