### ISSUE TITLE
deploy vm - when template not exists throw masive error

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#156]
STR:
1) try to deploy a vm with non existing template

Deploy App ended with status Failed with error: 01/Feb/2016 16:04:56 INFO Executing 'vCenter VM From Template' on app 'Test VM'...
01/Feb/2016 16:04:59 ERROR Error deploying app Test VM. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><ErrorCode>0</ErrorCode><ResponseInfo xsi:type="CommandExecutionFailedResultInfo" ErrorName="Script runner exited with exit code: 1" ErrorDescription="Traceback (most recent call last):&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA; exec code in run_globals&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\1db7f158-26cc-490d-8780-2f6175083b32\Deploy.zip\__main__.py&quot;, line 11, in &lt;module&gt;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\1db7f158-26cc-490d-8780-2f6175083b32\Deploy.zip\__main__.py&quot;, line 8, in main&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\1db7f158-26cc-490d-8780-2f6175083b32\Deploy.zip\driver.py&quot;, line 27, in execute&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py&quot;, line 5127, in ExecuteCommand&#xD;&#xA; raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;&#xA;qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.&#xD;&#xA;&#xD;&#xA;Error description: 01/Feb/2016 16:04:58 INFO action:START command_name:execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:58 INFO connecting to vcenter: 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:58 DEBUG connection params: host: 192.168.42.110 username: administrator@vsphere.local port: 443&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:58 INFO Starting new HTTPS connection (1): 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:58 DEBUG &quot;GET //sdk/vimServiceVersions.xml HTTP/1.1&quot; 200 552&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 INFO connected to vcenter: 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 INFO executing command: execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 DEBUG command params: 'vim.ServiceInstance:ServiceInstance',&lt;models.DeployDataHolder.DeployDataHolder object at 0x02EF8A30&gt;&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 INFO cloning VM...&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 ERROR error has occurred while executing command: execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 ERROR 'NoneType' object has no attribute 'Clone'&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\common\wrappers\command_wrapper.py&quot;, line 62, in execute_command_with_connection&#xD;&#xA;&#xD;&#xA; results = command(*tuple(command_args))&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 13, in execute_deploy_from_template&#xD;&#xA;&#xD;&#xA; deploy_result = self.deployer.deploy_from_template(si, deployment_params)&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\vCenterShell\vm\deploy.py&quot;, line 22, in deploy_from_template&#xD;&#xA;&#xD;&#xA; clone_vm_result = self.pv_service.clone_vm(params)&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 398, in clone_vm&#xD;&#xA;&#xD;&#xA; task = template.Clone(folder=dest_folder, name=clone_params.vm_name, spec=clone_spec)&#xD;&#xA;&#xD;&#xA;AttributeError: 'NoneType' object has no attribute 'Clone'&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 INFO disconnecting from vcenter: 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:04:59 INFO action:END command_name:execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA;&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA;&#xD;&#xA; exec code in run_globals&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\__main__.py&quot;, line 56, in &lt;module&gt;&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\__main__.py&quot;, line 40, in main&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\vCenterShell\command_executer.py&quot;, line 209, in deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\common\wrappers\command_wrapper.py&quot;, line 62, in execute_command_with_connection&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 13, in execute_deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\vCenterShell\vm\deploy.py&quot;, line 22, in deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\c45a9ab4-9b60-4ecc-b524-d68dee058be7\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 398, in clone_vm&#xD;&#xA;&#xD;&#xA;AttributeError: 'NoneType' object has no attribute 'Clone'&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;"><ErrorParameters/></ResponseInfo></Response>

**Comment by doppleware** [comment]
We need to catch this error and return something sane, as it probably will appear a lot.

**Comment by doppleware** [comment]
Duplicate of #151

**Comment by doppleware** [comment]
duplicate of #251

**Comment by razaba** [comment]
now its looks like:"
Deploy App ended with status Failed with error: CloudShellAPIError: Command execution failed with error: 'ValueError'.
Error description: Virtual Machine Template with name test54 was not found under folder QualiSB/Alex
[collection is empty]
"
is it ok?

**Comment by TomerAdmon** [comment]
verified
