### ISSUE TITLE
Wrong vcenter credentials will throw massive error during deploy

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#158]
STR:
1) set wrong user or pass to vcenter resource
2) deploy vm

Deploy App ended with status Failed with error: 01/Feb/2016 16:14:08 INFO Executing 'vCenter VM From Template' on app 'Test VM'...
01/Feb/2016 16:14:14 ERROR Error deploying app Test VM. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><ErrorCode>0</ErrorCode><ResponseInfo xsi:type="CommandExecutionFailedResultInfo" ErrorName="Script runner exited with exit code: 1" ErrorDescription="Traceback (most recent call last):&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA; exec code in run_globals&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\b4616cf0-b341-4148-8e0b-aa7727e8963e\Deploy.zip\__main__.py&quot;, line 11, in &lt;module&gt;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\b4616cf0-b341-4148-8e0b-aa7727e8963e\Deploy.zip\__main__.py&quot;, line 8, in main&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\b4616cf0-b341-4148-8e0b-aa7727e8963e\Deploy.zip\driver.py&quot;, line 27, in execute&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py&quot;, line 5127, in ExecuteCommand&#xD;&#xA; raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;&#xA;qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.&#xD;&#xA;&#xD;&#xA;Error description: 01/Feb/2016 16:14:10 INFO action:START command_name:execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:14:10 INFO connecting to vcenter: 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:14:10 DEBUG connection params: host: 192.168.42.110 username: 1administrator@vsphere.local port: 443&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:14:10 INFO Starting new HTTPS connection (1): 192.168.42.110&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:14:10 DEBUG &quot;GET //sdk/vimServiceVersions.xml HTTP/1.1&quot; 200 552&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:14:14 ERROR error has occurred while executing command: execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:14:14 ERROR (vim.fault.InvalidLogin) {&#xD;&#xA;&#xD;&#xA; dynamicType = &lt;unset&gt;,&#xD;&#xA;&#xD;&#xA; dynamicProperty = (vmodl.DynamicProperty) [],&#xD;&#xA;&#xD;&#xA; msg = 'Cannot complete login due to an incorrect user name or password.',&#xD;&#xA;&#xD;&#xA; faultCause = &lt;unset&gt;,&#xD;&#xA;&#xD;&#xA; faultMessage = (vmodl.LocalizableMessage) []&#xD;&#xA;&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\f2724bf8-bc61-40b5-84e2-d55e1a51fcb8\Deploy From Template.zip\common\wrappers\command_wrapper.py&quot;, line 51, in execute_command_with_connection&#xD;&#xA;&#xD;&#xA; connection_details.port)&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\f2724bf8-bc61-40b5-84e2-d55e1a51fcb8\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 59, in connect&#xD;&#xA;&#xD;&#xA; si = self.pyvmomi_connect(host=address, user=user, pwd=password, port=port, sslContext=context)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 680, in SmartConnect&#xD;&#xA;&#xD;&#xA; sslContext=sslContext)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 239, in Connect&#xD;&#xA;&#xD;&#xA; keyFile, certFile, thumbprint, sslContext)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 344, in __Login&#xD;&#xA;&#xD;&#xA; x = content.sessionManager.Login(user, pwd, None)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVmomi\VmomiSupport.py&quot;, line 570, in &lt;lambda&gt;&#xD;&#xA;&#xD;&#xA; self.f(*(self.args + (obj,) + args), **kwargs)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVmomi\VmomiSupport.py&quot;, line 376, in _InvokeMethod&#xD;&#xA;&#xD;&#xA; return self._stub.InvokeMethod(self, info, args)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVmomi\SoapAdapter.py&quot;, line 1335, in InvokeMethod&#xD;&#xA;&#xD;&#xA; raise obj # pylint: disable-msg=E0702&#xD;&#xA;&#xD;&#xA;vim.fault.InvalidLogin: (vim.fault.InvalidLogin) {&#xD;&#xA;&#xD;&#xA; dynamicType = &lt;unset&gt;,&#xD;&#xA;&#xD;&#xA; dynamicProperty = (vmodl.DynamicProperty) [],&#xD;&#xA;&#xD;&#xA; msg = 'Cannot complete login due to an incorrect user name or password.',&#xD;&#xA;&#xD;&#xA; faultCause = &lt;unset&gt;,&#xD;&#xA;&#xD;&#xA; faultMessage = (vmodl.LocalizableMessage) []&#xD;&#xA;&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;01/Feb/2016 16:14:14 INFO action:END command_name:execute_deploy_from_template&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;&lt;type 'unicode'&gt;&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA;&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA;&#xD;&#xA; exec code in run_globals&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\f2724bf8-bc61-40b5-84e2-d55e1a51fcb8\Deploy From Template.zip\__main__.py&quot;, line 56, in &lt;module&gt;&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\f2724bf8-bc61-40b5-84e2-d55e1a51fcb8\Deploy From Template.zip\__main__.py&quot;, line 40, in main&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\f2724bf8-bc61-40b5-84e2-d55e1a51fcb8\Deploy From Template.zip\vCenterShell\command_executer.py&quot;, line 209, in deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\f2724bf8-bc61-40b5-84e2-d55e1a51fcb8\Deploy From Template.zip\common\wrappers\command_wrapper.py&quot;, line 51, in execute_command_with_connection&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\tomer.a\AppData\Local\Temp\f2724bf8-bc61-40b5-84e2-d55e1a51fcb8\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 59, in connect&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 680, in SmartConnect&#xD;&#xA;&#xD;&#xA; sslContext=sslContext)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 239, in Connect&#xD;&#xA;&#xD;&#xA; keyFile, certFile, thumbprint, sslContext)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 344, in __Login&#xD;&#xA;&#xD;&#xA; x = content.sessionManager.Login(user, pwd, None)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVmomi\VmomiSupport.py&quot;, line 570, in &lt;lambda&gt;&#xD;&#xA;&#xD;&#xA; self.f(*(self.args + (obj,) + args), **kwargs)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVmomi\VmomiSupport.py&quot;, line 376, in _InvokeMethod&#xD;&#xA;&#xD;&#xA; return self._stub.InvokeMethod(self, info, args)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVmomi\SoapAdapter.py&quot;, line 1335, in InvokeMethod&#xD;&#xA;&#xD;&#xA; raise obj # pylint: disable-msg=E0702&#xD;&#xA;&#xD;&#xA;pyVmomi.VmomiSupport.InvalidLogin: (vim.fault.InvalidLogin) {&#xD;&#xA;&#xD;&#xA; dynamicType = &lt;unset&gt;,&#xD;&#xA;&#xD;&#xA; dynamicProperty = (vmodl.DynamicProperty) [],&#xD;&#xA;&#xD;&#xA; msg = 'Cannot complete login due to an incorrect user name or password.',&#xD;&#xA;&#xD;&#xA; faultCause = &lt;unset&gt;,&#xD;&#xA;&#xD;&#xA; faultMessage = (vmodl.LocalizableMessage) []&#xD;&#xA;&#xD;&#xA;}&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;"><ErrorParameters/></ResponseInfo></Response>

**Comment by doppleware** [comment]
lowered priority because of autoload validation
