### ISSUE TITLE
Support connect/disconnect operation (dvSwitch)

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#16]
Implement the connect/disconnect VLAN operations on the TBD to support VLAN (create port group, remove port group)
The input is the vnic to connect and the VM

the command should use the default dvSwitch (defined on the vCenter, and the vCenter is defined in an attribute on the VM resource)

Here are the basic flow:
connect_vm_to_network(network_id, vm)
	get_network (assume that network exists)
	create_port_group
	associate_vm_to_port_group

create_get_network(network_name or network_id)
	return network

create_port_group(name, number_of_ports, vlan_type, dvSwitchName, vCenter)
       return port_group

delete_port_group(vCenter, dvSwitchName, portGroupName)

Connnect(vlanId (220, 200-220), trunk/access, vm_resource_name)
	- Port group name should be generated by 
	 'vm_res_name Auto/Trunk VLAN Id/Range'

vCenter Resource
  - Default dvSwitch Path
  - Default dvSwitch Name
  - Default port group path 
 

Logical_Resource
   -HostedInfo    <----->      vCenter
   -vCenter Name
   -UUID + Path

VLAN Service 
[VLAN ID]
[Trunk/Access]

**Comment by borismod** [comment]
I need some clarification on this story.

**Comment by alonagetzler** [comment]
note that those command should be associated with the vCenter resource and be connected commands accessible on the deployed app
