### ISSUE TITLE
Rename pools logic API commands

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#171]
- change from VLAN to Pool
- write in the description that those are beta methods

**Comment by doppleware** [comment]
We need an API for 'Checkout_From_Pool' the parameter object should a JSOn,  let discuss before implementing

**Comment by alonagetzler** [comment]
need to hide those APIs from 7.0, and update cloudshell-automation-api in PyPi so those methods won't be included there. we'll comlete those APIs in 7.1.

**Comment by doppleware** [comment]
What she said.

**Comment by alexazarh** [comment]
removed in trunk, need to merge to 7.0 and verify cloudshell-automation-api

**Comment by alexazarh** [comment]
Its merged to 7.0
Waiting for Valentine to fix bug in cloudshell-automation-api generator before we can update the cloudshell-automation-api  in 7.0
