### ISSUE TITLE
Create the built-in VLAN services pacakge

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#174]
We need to provide the default VLAN services as a built-in package that comes with CloudShell. This package will include:
1) VLAN Auto
2) VLAN Manual
3) default VLAN

It should also include an Applications category that is associated with the Global domain.

Need to make sure this package is OOB with CloudShell 7.0 installation

**Comment by alexazarh** [comment]
added "default VLAN" model

**Comment by alonagetzler** [comment]
there is a mistake in the description, the name of the default VLAN model should be "VLAN Default" (just the service model, the attribute itself can stay "Default VLAN")

**Comment by alexazarh** [comment]
The split of the packages will be done as part of #457
