### ISSUE TITLE
get unusable error when configuring vm cluster path to point at cluster

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#183]
use the following settings for a vcenter resource for labs vcenter (192.168.26.106)
Basically, the vm cluster path points at a cluster and this errors out with "Exception: None"
![image](https://cloud.githubusercontent.com/assets/7686953/12889001/80f85320-ce85-11e5-86a5-0e7cb594fa52.png)

error:
![image](https://cloud.githubusercontent.com/assets/7686953/12889086/ffb031ce-ce85-11e5-8c44-753479d82a6a.png)

get this error on deploy_from_template:
Error: Exception
Description: None
Parameters:

**Comment by TomerAdmon** [comment]
Nahum, can you reevaluate?
@nahumtimerman

**Comment by TomerAdmon** [comment]
not relevant any more since we have autoload. closing
