### ISSUE TITLE
Support snapshot commands

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#186]
As a sandbox user i want to work save a snapshot of my deployed app for later use in my sandbox flow

Add the following commands as connected commands to the vCenter:

## Save snapshot

Input: Snapshot Name

Output: error on failure, no output on success

Save snapshot should fail in case a snapshot with the same full name (case sensitive) exists, with message “A snapshot of this name already exist under this VM. Please select a different name for the VM snapshot.”

##  Restore snapshot

Input: Snapshot Name

Output: error on failure, no output on success

* The snapshot name should be the full path of the snapshot, which is unique. *
* Snapshot Name should have description to the input: “Please enter the full path of the VM snapshot, for example Snapshot1/Snapshot2.” 
* Snapshot Name is case sensitive, fail in case full name isn’t unique with message “Not possible to restore the snapshot, there are multiple snapshots under this VM with the name ‘<FULL_NAME>’.”

## Get snapshots

Inputs: none
Output: list of snapshot names (comma separated, full name of snapshot) / error on failure. 
* Get snapshots should return the full path of the snapshots

**Comment by alexazarh** [comment]
@alonagetzler We dont have capacity to develop this for 7.1. Did you hear something from Roni if the can help with this?

**Comment by TaiTheGreat** [comment]
@alonagetzler regarding Restore Snapshot - if the name of the snapshot is unique, then the fail message when trying to restore a snapshot with a name that already exists can't be "multiple snapshots" but rather "a snapshot", right?

**Comment by alonagetzler** [comment]
@TaiTheGreat I agree that the phrasing might be confusing. although the uniquness is something only we enforce and isn't enforced in vCenter so this might happen. maybe we should change it to "there are one or more snapshots under this VM with the same name"

**Comment by tornizanQ** [comment]
[Test](http://team:8080/tfs/Quali-Collection/QualiSystems/_testManagement#planId=125053&suiteId=154920)
