### ISSUE TITLE
Expose the Pool ID as an optional input on the VLAN services

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#189]
currently the default is take the domain name
need to add an attribute on the VLAN service - if empty, use the domain, if not empty use this value as the pool id

**Comment by GilGald** [comment]
What should be the name of the attribute ?

**Comment by alonagetzler** [comment]
the attribute should be Pool Name

**Comment by alonagetzler** [comment]
the behavior - if the attribute is left empty we take the domain name. if the user enters the domain name of the current logged in domain than its valid, but if the user enters the domain name of a different domains we should throw an error and not allocate a VLAN. this attribute should be associated with the VLAN services (VLAN Auto, VLAN Manual, VLAN Default) and not be a user input.

**Comment by GilGald** [comment]
So to sum up :
if pool name attribute value is empty \equals to current domain the value will be the current domain .
in any other case it will be the value that's in the attribute,unless the value is a domain that is not the current domain,in that case we will throw an error.
@alonagetzler

**Comment by GilGald** [comment]
1.what about value like  "    " (four blank spaces)? is it valid? 

2.what if we are adding a VLAN that is not as same as a domain name and a few days later We add a new domain name that is just like the pool name attribute we just added a few days ago?
any new connection to that VLAN will fail

@alonagetzler @alexazarh

**Comment by alonagetzler** [comment]
1. blank space/s should be treated like empty
2. should throw the same error we throw when the domain already exists. the error should explain that this pool is used in another domain.

**Comment by GilGald** [comment]
So what should a user do if he already uses a pool name that suddenly became a domain name?

**Comment by alonagetzler** [comment]
that's really an edge case, and as long as we give a clear error the domain admin can adjust the VLAN service and rename the pool

**Comment by GilGald** [comment]
OK
