### ISSUE TITLE
Implement pool logic for VLAN allcation

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#19]
I want to manage a pool of items (VLANs,etc.) and use API to get items from the pool based on defined selection policy. For now we are implementing a 'numeric' pool, but the architecture should support other types of item (i.e IPs, strings, licenses etc.)

GetItemFromPool([PoolID], [reservationId], [Selection_Criterion], [Isolation_Level])
ReleaseFromPool([PoolID], [reservationId], [Selection_Criterion])

Examples:
GetItemFromPool("Auto-Global",reservationId, Criterion.NextUnusedNumeric, IsolationLevel.Exclusive) - Unavailable to this and other reservations
GetItemFromPool("Auto-Global",reservationId, Criterion.SpecificNumeric(2999), IsolationLevel.Reservation) - Unavailable to other reservations (available to this one)
GetItemFromPool("Auto-Global",reservationId, Criterion.SpecificRanges(2999, 3500), IsolationLevel.None) - Available to everyone

We also want to add to the reservation end event the logic to remove all pool items for that reservaiton Id.

**Comment by yoavEkshtein** [comment]
I have a few questions about this:

1. how do I define a new pool? 
2. where can I check the pool's bounderies? can I expand or  shrink them?
3. do I have a method to extract an item's state , without taking it?
4. what is the logic of IsolationLevel? if there are two requests with different iso levels , how does it work? 
5. if I have a pool item in a reservation and the reservation ends , is it released?

**Comment by alonagetzler** [comment]
1. you don't. the pool isn't "modeled" in the system, we have a table with all the requests, the isolation level and the selection criteria. each item in the pool has a reservation id, owner id (vlan service or connector), the values itself (vlan id or range) and the isolation level (exclusive/reservation/none).
2. there are no pool boundaries, when you request an vlan id on connect it takes the request, see what's already allocated and decides accordingly.
3. no
4. say you have an VLAN ID 200 taken by ConnectorA in ReservationA as Exclusive, now in another/same reservation there will be an autoVLAN service that has an allocation range 200-204, isolation level Exclusive and selection criterion NextUnusedNumeric --> once connecting something to this autoVLAN service it will figure out that 200 is already exclusively used and select the next unused numeric (201). a new entry will be added for VLAN ID 201 with the autoVLAN service as owner, the reservation ID and the isolation level for this will be exclusive as well.
5. there are two ways in which an item is released from the pool - on reservation end all items associated with this reservation are released from the pool, and on removal of the item's owner from the reservation (connector OR vlan service) the item is also released from the pool.
