### ISSUE TITLE
Add Q-in-Q support in the VLAN services

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#195]
We should actually pass ALL of the VLAN service attribute to the connect/disconnect command.

A new attribute should be added to the VLAN services, and its value should be passed to the Connect command on the L2/L3. The vCenter Connect command should ignore it, the L2/L3 Connect command will use it.

Attribute name: QnQ
Type: boolean
Default: False

Attribute name: CTag
Type: string
Default: empty
Possible values: empty / VLAN ID / VLAN range

Once QnQ is equal to true, should pass to the Connect command the following parameter "qnq".

**Comment by alexazarh** [comment]
@alonagetzler 
Please explain what the following means:
"Once QnQ is equal to true, should pass to the Connect command the following parameter "qnq"."
