### ISSUE TITLE
Support "connect" command on physical devices

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#196]
For physical devices when selecting which resource to run the "connect" on (when the VM details are empty) check:
1) if the resource itself (root) is an L2/L3 (use the same logic as in CVC) run the command on this resource
2) if not, find the resource (endpoint) that is physically connected to and run the connect on that resource

enhancement - When a connected visual connector is in a 'connecting' state, we want to show some indication to the user

**Comment by alexazarh** [comment]
Visual connector animation: 
https://jsfiddle.net/yoelshachar/ydp3xf5b/

**Comment by alexazarh** [comment]
The CVC enhancement will be completed later. I added an issue for that #224
