### ISSUE TITLE
Align to final data model

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#199]
The final package should contain:
- deployment service model and driver
- orchestration service model and driver
- vCenter family model and driver
- resource template for the vCenter
- setup and teardown scripts

See final data model for the deployment services and the vCenter in (including an XML that defines it) here:
http://qs-srv-confluence:8090/display/QP/vCenter+and+deployment+services+attributes+and+autoload+logic

The final package shouldn't include:
- virtual network services (separate package which will come OOB with CloudShell)
- predefined app (a.k.a "VM deployment")
- any resource or environment

Logic that should be in place:
1) in the VM deployment, the defaults for VM Cluster, VM Storage, VM Resource Pool and VM Location should be taken from the vCenter unless there is a none-empty value in those attributes on the deployment service instance. DONE

2) Auto Power On, Auto Power Off, Wait for IP and Auto Delete attribute values should be copied to the VM Properties of the deployed app. - Done in #339

3) In the setup/teardown orchestration, the defaults for Auto Power On, Auto Power Off, Wait for IP and Auto Delete should be taken from the vCenter unless the VM Properties hold different values for those attributes.  Done in #339

4) the Default dvSwitch, Holding Network, Default Port Group Location, Shutdown Method and OVF Tools Path should be taken from the vCenter resource DONE

**Comment by borismod** [comment]
Gap: verify override of the attributes work correctly
