### ISSUE TITLE
Removal of connection does not remove the potgroup connection from the vm

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#208]
1. connect a vm to a vlan
2. remove the connection
3. check the vm on the vcenter

result:
nic is still connected to the portgroup

**Comment by borismod** [comment]
@yoavEkshtein thanks for opening this
@alonagetzler is it a bug or a feature?

**Comment by nahumtimerman** [comment]
relevant integration test is ConnectScenarios.Disconnect_Peer_To_Peer_Apps currently in Ignore

**Comment by TomerAdmon** [comment]
Verified
