### ISSUE TITLE
connecting a few vlans while deploying app, only one is connected

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#209]
1. connect a few vlans to undeployed app (disconnected cvcs)
2.  deploy the app

result:
there are multiple network assignments in the vcenter , but only one is defined at the end. my guess is that they overwrite each other

![image](https://cloud.githubusercontent.com/assets/16865064/13104713/6f56e5e4-d567-11e5-8e71-1e241ae10227.png)

**Comment by borismod** [comment]
@yoavEkshtein this is work in process connect #200. @TomerAdmon are you sure we need such bugs?

**Comment by borismod** [comment]
[![selfie-1](http://i.imgur.com/2vSB8mI.png)](https://github.com/thieman/github-selfies/)

**Comment by TomerAdmon** [comment]
fixed. verified.
