### ISSUE TITLE
Test performance of suspected areas

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#21]
Test our 'get templates' method on the simulator and measure its performance with a large number of objects.
We need to get an understanding of how much this slows us down to see if its problem.
For example: Performance for 100/1000/5000 objects in the folder.

**Comment by alexazarh** [comment]
We also need to test the find by UUID method when its invoked without a datacenter obj and when we provide a datacenter obj (requires to find the datacenter obj beforehand using its name).
