### ISSUE TITLE
Add new entity of type "hosted on"

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#22]
Per each deployed app this entity will hold information on the VM/s that the app is hosted on. The hosted on entity will be associated with (1) a list of attributes, (2) commands (=scripts), (3) list of NICs

This entity is a new CloudShell entity that will be associated with each Lab Resource (if exists), and GetResourceDetails API command will returns the hosted-on entity's deatils.

**Comment by JoanWrabetz** [comment]
Alona,

I am confused about this new entity.  I do not think that we need this to associate an app with its vm.  We don't support multi GM apps and we already have a higher level interface for apps.  I don't see why we would add this for all resources.  Maybe the description is the problem.  In any case, this is not a requirement, it is an implementation choice, one that will have serious design implications.  I do not think we want this added until a more detailed discussion happens.

Best regards,

Joan

Sent from Outlook<http://aka.ms/Ox5hz3>

_____________________________
