### ISSUE TITLE
Add VlanService attributes to connectionParams in setVlanAction

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/vCenterShell#220]

**Comment by TomerAdmon** [comment]
@alexazarh  - how can i verify this?

**Comment by alexazarh** [comment]
The json request is written to the server log with info severity so you can
adjust the logging severity accordingly and see the json in the log

Best regards,
Alex Azarh

**Comment by yoavEkshtein** [comment]
verified on 1.0.176
