### ISSUE TITLE
Error message not returned on Connect Bulk error

### ISSUE THREAD

**Issue by razaba** [QualiSystems/vCenterShell#226]
STR:
Try to connect when no vnic is available the following json is returned:

{
  "driverResponse": {
    "actionResults": [
      {
        "success": false,
        "updatedInterface": null,
        "errorMessage": "",
        "infoMessage": "",
        "actionId": "60536e2a-7266-4a9e-93e1-58099d496ec7_20b1fc8b-b7a2-4489-a556-35f70ee022e5",
        "type": "setVlan"
      }
    ]
  }
}

**Comment by tornizanQ** [comment]
still reproduces

**Comment by tornizanQ** [comment]
verified
