### ISSUE TITLE
Deploy app responsiveness in case IP is IPv6 or empty

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#246]
Timeout for refresh IP is 10 minutes.
If ip the machine generates is IPv6 (the fallback when IPv4 can't be found on dhcp server because addresses were tapped out) or when an ip simply isnt calculated, deploy app will wait for 10+ minutes and then error out. aside from responsiveness for users, this causes tests to fail in an ugly way after a long time

**Comment by borismod** [comment]
Resolved as part of:
connect #346
