### ISSUE TITLE
Deploy vm isn't working if using \ instead of /

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#248]
try to deploy with Vm location that has \ for indicating a folder --> get an error.
try to deploy the same but changing the \ to / and it will work

**Comment by TomerAdmon** [comment]
Reopen

![image](https://cloud.githubusercontent.com/assets/12639815/14081340/f4f66c04-f512-11e5-924f-e05ef32f0c11.png)

**Comment by razaba** [comment]
I talk with Roni, and we fixed it at vm template and not at the vm location, because we don't have validations at that stage, bu we have autodiscovery in for the vcenter

**Comment by TomerAdmon** [comment]
Change priority regarding @razaba  command, move to backlog
