### ISSUE TITLE
vcenter resource template: cant see full attribute names

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#250]
some attributes get cut and it just looks like an odd form for something that should give users confidence and ease of use

![image](https://cloud.githubusercontent.com/assets/7686953/13379416/c26dcddc-de2d-11e5-9866-7c050621fabb.png)

**Comment by alexazarh** [comment]
Thats a usability bug that should be fixed (if at all) by another scrum.
@nahumtimerman - please talk with Menny about this  bug
