### ISSUE TITLE
Connectivity: if VM doesn't have the number of Nics as the number of connected routes no error appears

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#252]
STR:
1) have a template in Vcenter with 1 nic
2) add app to reservation, connect 3 vlans to it.
3) deploy the app

result:
user will see "connection failed" on the route but there is no error message / description in the activity feed / pop-up message

**Comment by doppleware** [comment]
Lets check if this still happens, if so we need to make sure to handle

**Comment by razaba** [comment]
@doppleware 
the reason when started using the api command: "ConnectRoutesInReservation", the return value is the routes that we tried to connect.
from the return value I cannot extract whether the route is connected or not.

how should I resolve the issue?
1. do api call for each route and check its status? (performance loss)
2. adding an attribute to each of the route in the resolve containing its status? (might break the api)
3. other thing you might think about...

**Comment by TomerAdmon** [comment]
@doppleware  @razaba  - do we still need something for this issue? can we verify ? i think now we will see a "no vniic available" error....

**Comment by razaba** [comment]
should be ok, it can be verified

**Comment by tornizanQ** [comment]
Verified
