### ISSUE TITLE
Connectivity: when D.App is destroyed it not returning the Nic to the Default value "Anetwork"

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#256]
STR:
1. have a reservation with 2 D.apps with connected CVC between them
2. Then destroy one of them
BIR: if the Nic of the exist D.App is not returning to the Default Vlan "Anetwork"

**another scenario:**
title: Removing a CVC as part of P2V is not returning the Nic to the Default Network
STR:
1. Have a reservation with D.App that connected to Vlan  (connect the CVC)
2. remove the CVC
BIR: if the D.App's Nic is not returning to the default network "Anetwork"

**another scenario:**
title:when removing "partially connected" CVC it not returning the NIC to the default value "Anetwork" 
STR:
1. have reservation with 2 APPs
2. add CVC connection between the 2 apps
3. then deploy one app (the alias name changed to "partially connected")
4. Then remove the CVC connection
Expected res:
after removing the CVC connection it supposed to return the NIC of the VM to the default value "Anetwork" and it still on the chosen Vlan

**Comment by razaba** [comment]
AS we understand the problem is that disconnect is not called on the second app when one of the apps is destroyed in a p2p (although the connector is removed)

**Comment by doppleware** [comment]
please also close #404 which is duplicate of this one when fixing

**Comment by doppleware** [comment]
Also check if #324 is also fixed by this and close also

**Comment by alexazarh** [comment]
Scenario #2 & #3 are fixed
Scenario #1 is still open (when deleting a deployed app)

**Comment by alexazarh** [comment]
Scenario #1 also fixed
