### ISSUE TITLE
It's impossible to change the vCenter login credentials until the vCenter instance is closed and re-opened

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#270]
If a user wants to change the vCenter credentials  he need to change it via the RM and wait until a new instance of the vCenter will be opened with the new credentials

**Comment by Yairzeri** [comment]
relates to any attributes changed in the vCenter resource , the changes are done only on a new instance.

**Comment by TomerAdmon** [comment]
seems to be fixed!
