### ISSUE TITLE
Deployed app is possible when having a wrong VM Storage

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#282]
always created under eric ds cluster

*Done this after killing the instance (to validate that the changed are saved)

**Comment by Yairzeri** [comment]
The empty attribute value is specified in the vCenter resource.
The attribute is empty in the deployment options services.
![image](https://cloud.githubusercontent.com/assets/17525950/13629698/809e5cba-e5e3-11e5-8723-68c2eb9799f6.png)

![image](https://cloud.githubusercontent.com/assets/17525950/13629704/8d5d9416-e5e3-11e5-88a9-69b90f09f0d6.png)

**Comment by alonagetzler** [comment]
that's not a bug, if no datastore is defined we should automatically select. Obviously when there is a selected datastore we should use it.
