### ISSUE TITLE
CVC: Selected Network Attribute is empty when the connection is between Vlan to D.App

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#286]
1. have reservation with D.App and Vlan service
2. add a CVC between them
3. connect the CVC

BIR: if the Selected Network Attribute is empty and not with the Vlan ID

**Comment by alexazarh** [comment]
From what I know its the desired behavior...
@alonagetzler / @doppleware - please confirm

**Comment by alonagetzler** [comment]
its as designed, not a bug,

**Comment by TomerAdmon** [comment]
closing after alona's comment below
