### ISSUE TITLE
Please stop flooding the CodeBetter CI build queue

### ISSUE THREAD

**Issue by adamralph** [QualiSystems/vCenterShell#289]
![image](https://cloud.githubusercontent.com/assets/677704/13402013/b7029194-df0e-11e5-822a-e6ad63071284.png)

You currently have ~50 builds in the queue. Can you please remove them and take steps to make sure the queue does not get flooded again.

Many thanks.

**Comment by borismod** [comment]
@adamralph we're sorry for making so much noise in the TC. The build configuration have been just deleted.

**Comment by adamralph** [comment]
Thanks @borismod
