### ISSUE TITLE
P2V: Not removing(releasing) the Vlan ID after deleting the Vlan Service

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#291]
steps to rep:
1. have a reservation with D.App and a vlan Service
2. add CVC and connect it
3. Check the vlan ID that was chosen
4. remove the CVC 
5. delete the Vlan service

* it should work even when skipping on step 4.

actual res:
the vlan ID is still in use in our DB
-> there is a different bug about deleting the port group in Vpshere

expected res:
The Vlan ID is not in use anymore -> supposed to remove it from our DB

for more convenient way please use yoav package that include a driver that pull out the vlan ids that are in use

**Comment by DoronFried** [comment]
yoav package:
\\qsnas1\Shared\Doron\Yoav package - Vlan pool checker\
* import the package -> configure the "lepool" resource in RM-> run the driver in the reservation

**Comment by doppleware** [comment]
Check if still happens

**Comment by TomerAdmon** [comment]
Can't reproduce.
