### ISSUE TITLE
Non informative error is raised when the installation script has an error

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#299]
This non informative error appears on the error notification:
"Deploy App ended with status Failed with error:"

in the full activity log this error appears:
Error: Script runner exited with exit code: 1
Description: Traceback (most recent call last):
  File "C:\Users\yair.z\AppData\Local\Temp\2af7ea1a-b430-4c99-bea7-486b5a9a8b95\Installation1.py", line 1, in 
    file = open(bla)
NameError: name 'bla' is not defined

Parameters:

**Comment by alonagetzler** [comment]
The message should  include the fact that the installation step has failed
