### ISSUE TITLE
ConnectRoutesInReservation: Getting Activation Error when trying to connect a CVC

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#300]
1. Have a reservation with D.App and Vlan service
2. then add CVC request between them
3. then connet the cvc with TestShell API ConnectRoutesInReservation from studio

actual result:
it succeed to connect but you get Activation Error in studio

![image](https://cloud.githubusercontent.com/assets/17528399/13430017/d78b6a36-dfcb-11e5-8cd3-3821b8669cc9.png)

**Comment by alexazarh** [comment]
@DoronFried its fixed. You can verify :)

**Comment by TomerAdmon** [comment]
Verified
