### ISSUE TITLE
ConnectRoutesInReservation: Can't connect Route request through the API

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#301]
1. have a reservation with 2 bridges that physically connected to a patch panel
2. add route request between them
3. try to connect the route with ConnectRoutesInReservation TestShell API from studio

BIR: 
impossible to connect the route and you get error msg "visual connector between b1 and b2 not found"

![image](https://cloud.githubusercontent.com/assets/17528399/13430240/ec472fc2-dfcc-11e5-92e9-c40531fe89d0.png)

**Comment by alexazarh** [comment]
@DoronFried its fixed. You can verify.

**Comment by alexazarh** [comment]
Not a bug. The endpoints should be the full name of the endpoint. Example: "b1/p1".
I update the error message to be more descriptive.

**Comment by TomerAdmon** [comment]
Verified
