### ISSUE TITLE
When using setup script and it fails, when trying to re run the setup manually its doesn't the commands returns completed successfully but they doesn't

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#302]
STR 
Have an environment with setup script and vm deployment
run the setup script and stop it in the middle so the setup will finish with an error
Run the setup command again manually

BIR
The commands seems to run from their correct possision with "completed successfully" but they haven't done anything they were supposed to.

**Comment by TomerAdmon** [comment]
Verified
