### ISSUE TITLE
[API user] getting the deployed app after running "Deploy App" on orchestration driver

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#303]
As an API user, run "Deploy App" on orchestration driver.
you have no way to know what the name of your deployed app will be so you're stuck

**Comment by nahumtimerman** [comment]
Solution confirmed with Alona & Meni:
orchestration driver command "Deploy App" will print to output
"<deployed app name> deployed successfully"

**Comment by alexazarh** [comment]
@nahumtimerman just print this string to the reservation output?

**Comment by nahumtimerman** [comment]
fixed

**Comment by TomerAdmon** [comment]
Verified

**Comment by TomerAdmon** [comment]
Closed
