### ISSUE TITLE
Deleting Vlan that having more than one Connected CVC is disconnecting the CVCs one by one

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#305]
STR:
1. have a reservation with Vlan service
2. have more than one D.APP that is connected to the Vlan Service (connected CVCs)
3. then delete the Vlan service

BIR:
if it disconnecting the CVCs one by one and not in parallel

![removing vlan with several connected cvc](https://cloud.githubusercontent.com/assets/17528399/13431960/43870468-dfd4-11e5-9e74-aed37027e4fa.gif)

**Comment by alonagetzler** [comment]
should happen in parallel

**Comment by alonagetzler** [comment]
@tornizanQ  please open in TFS for Shay and cancel this one

**Comment by tornizanQ** [comment]
Opened in TFS
