### ISSUE TITLE
connectivity fails on deploy app visually connected to vlans with specific NICs configured

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#306]
1. have a reserved app in reservation
2. drag visual connectors to vlans such that they have the attribute Requested Target Vnic Name which is filled with "Network Adapter 1", "Network Adapter 2" etc.
 3. deploy the app

defect is reproduced if get an error like this:
command_json_result={"driverResponse": {"actionResults": [{"success": "False", "updatedInterface": "None", "errorMessage": "Traceback (most recent call last):\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\commands\\connect_orchestrator.py\", line 75, in _set_vlan_bulk\n    default_network, reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\commands\\connect_dvswitch.py\", line 50, in connect_to_networks\n    si, vm, mappings, default_network_instance, reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\vm\\dvswitch_connector.py\", line 72, in connect_by_mapping\n    reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\vm\\portgroup_configurer.py\", line 39, in connect_vnic_to_networks\n    mapping, vnic_mapping, vm.network, default_network, reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\vm\\vnic_to_network_mapper.py\", line 22, in map_request_to_vnics\n    raise Exception('the vnic: {0} does not exist'.format(request.vnic))\nAttributeError: 'ConnectRequest' object has no attribute 'vnic'\n'ConnectRequest' object has no attribute 'vnic'", "infoMessage": "", "actionId": "e8cd5f40-6bf3-493d-ab1f-bba8efc57c08_8b2582e5-6f76-487a-9e33-419f8c7f5036", "type": "setVlan"}, {"success": "False", "updatedInterface": "None", "errorMessage": "Traceback (most recent call last):\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\commands\\connect_orchestrator.py\", line 75, in _set_vlan_bulk\n    default_network, reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\commands\\connect_dvswitch.py\", line 50, in connect_to_networks\n    si, vm, mappings, default_network_instance, reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\vm\\dvswitch_connector.py\", line 72, in connect_by_mapping\n    reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\vm\\portgroup_configurer.py\", line 39, in connect_vnic_to_networks\n    mapping, vnic_mapping, vm.network, default_network, reserved_networks)\n  File \"c:\\users\\nahum-t\\appdata\\local\\temp\\tmpunovl8.zip_env\\vCenterShell\\vm\\vnic_to_network_mapper.py\", line 22, in map_request_to_vnics\n    raise Exception('the vnic: {0} does not exist'.format(request.vnic))\nAttributeError: 'ConnectRequest' object has no attribute 'vnic'\n'ConnectRequest' object has no attribute 'vnic'", "infoMessage": "", "actionId": "cc3fa758-6b0c-4791-b799-148957b960cb_8b2582e5-6f76-487a-9e33-419f8c7f5036", "type": "setVlan"}]}}=command_json_result_end

**Comment by TomerAdmon** [comment]
@nahumtimerman  - Nahum, please verify
