### ISSUE TITLE
Merge the package with CloudShell suite

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#312]
the vCenter package (including the vcenter datamodel, the deployment services, orchestration service, virtual network services and the setup+teardown) should be part of CloudShell suite.
the zipped package should be located in "%/CloudShell/Data/Server/QualiSystems/Quali/Server/Config" folder and then the installer imports the package

**Comment by doppleware** [comment]
This was done by @TomerAdmon
