### ISSUE TITLE
vm deployment with wrong template route will bring unclear error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#313]
STR
Have a VM deployment with a false template rout in it 
Create a reservation
add the VM deployment app in it
run the deploy command 

BIR

![image](https://cloud.githubusercontent.com/assets/17527106/13457915/3c7746de-e073-11e5-81e9-9bae394cf261.png)

**Comment by doppleware** [comment]
duplicate of #156
