### ISSUE TITLE
Synchronize connect/disconnect requested in the Connectivity Service

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/vCenterShell#318]
Synchronize connect/disconnect requested in the Connectivity Service using the generic lock.
Do the lock on the CVC guid.

**Comment by alonagetzler** [comment]
Alex: Its not really a bug, it’s a tech story. It should ensure there will be no race conditions.

**Comment by alexazarh** [comment]
We will synchronize the "connect/disconnect" requests on connector endpoints. If one of the connector endpoints is locked the request will wait until it's releases
