### ISSUE TITLE
Move Deployed App creation to the app orchestrator

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#32]
see the flow here:
http://qs-srv-confluence:8090/display/QP/App+Orchestration+Flow+-+vCenter+VM+deployment

need the deploy command to only create the VM on the vCenter and then the app orchestration should create the "deployed app" resource based on the results it got from the deploy (no use of the new API yet). the orchestration can be based on the temp app orchestration driver written by Meni.

**Comment by alexazarh** [comment]
I have a full demo of this working :)
