### ISSUE TITLE
When creating a new enviroment and connecting two deployment app the connector is visual connector instead of cvc

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#320]
STR
Create a new environment 
Add two VM Deployment apps
Connect the apps via p2p

BIR
The connection is visual instead of cvc
![image](https://cloud.githubusercontent.com/assets/17527106/13464056/ec7a4512-e097-11e5-8412-16dc15215775.png)

**Comment by doppleware** [comment]
Could not reproduce on latest

**Comment by TomerAdmon** [comment]
could not repreduce. closing.
