### ISSUE TITLE
When having more than one Default Vlan service in a reservation\gloabl or non global domain, which Vlan it will pick?

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#323]
when connecting P2P and there are more than one Default Vlan in the reservation\ global or non gloabl domain it will pick a vlan id from one of the default vlans.
right now it picking randomly one of the default vlans services. 
BUT we need to do it in some order no matter in which order (like alphabetically)... (we want to do it because we don't want to tell customers that it picking randomaly which vlan id to use)

**Comment by doppleware** [comment]
By design
