### ISSUE TITLE
Getting unclear error msg when insert invalid values in the "Requested Source\target Vnic Name"

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#325]
![image](https://cloud.githubusercontent.com/assets/17528399/13468332/c865f258-e0aa-11e5-9c67-7a62e62e42db.png)

**Comment by doppleware** [comment]
We need to catch and add an error - 'No network adapter by that name exists: {name}'
Also - can we try to check if its a number first, if so try to resolve by interface number?

**Comment by razaba** [comment]
no.... the name of the attribute has changed from vnic to vnic_name and the raise ValueError raised an exception...

**Comment by TomerAdmon** [comment]
@alonagetzler  - i think the error should be rephrase:
![image](https://cloud.githubusercontent.com/assets/12639815/14061310/50b3aca4-f38e-11e5-8950-1f895f35d203.png)

**Comment by alonagetzler** [comment]
indeed we should rephrase, see Roni's error above - 'No network adapter by that name exists: {name}'

**Comment by TomerAdmon** [comment]
@razaba  - reopen, please see Alona's comment

**Comment by tornizanQ** [comment]
Verified
