### ISSUE TITLE
Wrong behavior When connecting P2P to a vm that doesn't have available Nics

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#329]
STR:
1. have a reservation with 6 D.Apps.
2. add CVC request from 5 D.Apps to one D.App
3. connect 4 CVCs
4. try to connect the 5 CVC

Actual result:
the CVC is straight line but with alias "Connection Failed". its behavior is like partially connected -> the 5 CVC is configured with Vlan Id and the second VM one of his nics has this vlan

Expected result:
need to consult with product

![image](https://cloud.githubusercontent.com/assets/17528399/13488013/25cb32c4-e127-11e5-901d-f51b5b85c160.png)

**Comment by alonagetzler** [comment]
The expected behavior is to show "partially connected" and the connection should be in connected state (so you can disconnect it and by that clear the VLAN configuration on the vNIC that was able to connect).

**Comment by alexazarh** [comment]
Are we sure that this is a bug?
Please refer to the L2 Connectivity Design:
http://qs-srv-confluence:8090/display/QP/L2+Connectivity+and+VLAN+Improvements+-+Design

Here is the relevant part:
![image](https://cloud.githubusercontent.com/assets/6730546/13850636/7cdbebf2-ec63-11e5-878c-e6582f7f8683.png)

**Comment by alonagetzler** [comment]
as discussed, "partially connected" should be considered "Connected" (full line)

**Comment by alexazarh** [comment]
Following our internal discussion today: This is not a bug. Its the expected behavior.
If we try to connect the two sides and one of them fails than we want to have the option to disconnect.

**Comment by yoavEkshtein** [comment]
closed according to the comment by Alex
