### ISSUE TITLE
Move VM deployment/deletion to the vCenter resource

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#33]
the Deploy command on the deployment service should just call a "Deploy" command on the vCenter resource which should actually create the VM in the vCenter and return the VM Data.

the "delete" command on the VM resource should also move to the vCenter and be a connected command accessible on the deployed app resource (currently use regular connected command with physical connection) *note that scripts might not support connected commands and we'll need to wrap it in a driver

**Comment by alexazarh** [comment]
The Deploy command already behaves as described.

Do you mean to use an authoring driver for the destroy command?

**Comment by alonagetzler** [comment]
We just need to make sure both commands exist on the vCenter and not on the resource in the reservation.
The commands on the resource in the reservation will become obsolete when we get the connected commands from the 'hostedon' info....

**Comment by alexazarh** [comment]
There is a bug on the server side that prevents a deployed app resource to be deleted, but the VM is removed successfully  from the vCenter. Bug #147776
Other than this, the task is done

**Comment by TomerAdmon** [comment]
PV:
delete vm test plan will take place as part as task #9 by Yoav. 
this test plan will coved deploy only.
@yoavEkshtein

**Comment by TomerAdmon** [comment]
PV:
deploy vm test plan will take place as part of task #8 by Yoav.
