### ISSUE TITLE
Error when using the "Default Sandbox Setup" driver

### ISSUE THREAD

**Issue by omerbotenski** [QualiSystems/vCenterShell#335]
STR:
Create an environment using the Default Sandbox Setup + Teardown you get with the system.
Make sure the environment contains two apps connected to each other.
Reserve the environmet.

BIR if you get this error:

Error: General
Description: Failed to find a valid script to execute as a Setup command. Script must have an alias of 'Setup script' and have no parameters.
Parameters:

![image](https://cloud.githubusercontent.com/assets/17544324/13493051/4028f512-e144-11e5-9602-f891300273c3.png)

The alias of the driver is actually 'Setup script' so either the error message is wrong or something in the driver

**Comment by TomerAdmon** [comment]
please provide STR.

**Comment by TomerAdmon** [comment]
make sure to add setup & teardown scripts in the topology properties page, this will solve the issue.

**Comment by omerbotenski** [comment]
Got it

Thanks,

Omer Botenski
