### ISSUE TITLE
deploy app that is connected to DUT will fail with "Port not in reservation" error

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#336]
STR:
1) have a reservation with undeployed app connected to DUT
2) deploy the app

result:
error message:
"Deploy App ended with status Failed with error: DUT1/Blade 1/Port 2 not found in reservation"

**Comment by alexazarh** [comment]
ready for test

**Comment by TomerAdmon** [comment]
Verified
