### ISSUE TITLE
P2P with DUT will not work if L2 is not in the reservation

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#337]

**Comment by alexazarh** [comment]
There are 2 options to solve this:
1) Use the magic tag in the python driver to allow running commands on the L2 when its not in the reservation
2) Make the ApplyConnectivityChanges a remote command on the DUT

**Comment by alonagetzler** [comment]
use the magic tag in the python driver of the L2

**Comment by TomerAdmon** [comment]
Cool, 
I will fix my L2 driver....
Alona, can you add this to the Shells template?

**Comment by TomerAdmon** [comment]
closing (add the magic tag to the L2 mock driver)
