### ISSUE TITLE
An unclear error notification appears when trying to deploy vm from image and the image is not found

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#342]
STR 
Have a reservation with a vm deploy  from image app that directed on a folder that has not gotten any ovf file in it 
Run the deploy app command 

BIR
unclear error appear
![image](https://cloud.githubusercontent.com/assets/17527106/13496469/06d7be46-e159-11e5-8e55-c7a01fe65a76.png)

**Comment by TomerAdmon** [comment]
Verified
![image](https://cloud.githubusercontent.com/assets/12639815/13913832/ef7e3448-ef52-11e5-9601-42531494769a.png)
