### ISSUE TITLE
When deploying an app without vmware tools returns an unclear error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#343]
have a template that vnware tools is not installed on it 
create a reservation 
Add an undeployed app that use the template without the vnware tools 
Run deploy app command 
BIR
unclear error appears
![image](https://cloud.githubusercontent.com/assets/17527106/13496674/448e3eb2-e15a-11e5-8a79-cf1c7b93dba2.png)

**Comment by doppleware** [comment]
Deploy shouldn't fail if vmware tools not installed, but IP should not be checked

**Comment by razaba** [comment]
@tornizanQ 
ok.. 
Tor, can you send me a template that I can reproduce this bug

**Comment by TomerAdmon** [comment]
@razaba 
you can use the Alex/empty

**Comment by razaba** [comment]
now it skips the refresh if vmware tool are not install

**Comment by TomerAdmon** [comment]
Verified
