### ISSUE TITLE
When using vm deployed from image only, the deployed vm is installing in different path than defined by user

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#345]
STR 
Have a reservation with undeployed app from image that directed to install the vm on QualiSB/New by changing the value of vm location attribute from the vCenter in the rm
Run deploy app command

BIR 
The deployed app from image is installed in QualiSB/Alex no matter the vm location attribute value

**Comment by TomerAdmon** [comment]
Seems ok now.
