### ISSUE TITLE
vm deployment from image when vmdk file is missing brings unclear error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#347]
vm deployment from image when vmdk file is missing brings unclear error

![image](https://cloud.githubusercontent.com/assets/17527106/13497737/9387425c-e15f-11e5-98ae-56064e506ddb.png)

**Comment by TomerAdmon** [comment]
seems like the same error: 
![image](https://cloud.githubusercontent.com/assets/12639815/13997131/397e6fb2-f139-11e5-9e7f-7a0cc2862bae.png)

**Comment by alonagetzler** [comment]
we should fix this error
