### ISSUE TITLE
The deployment logic does not changed according to the change of specific vCenter resource attributes

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#348]
Change the following attributes on the vCenter resource:
- Default dvSwitch
- Default Port Group Location
- Holding Network
- VM Cluster
- VM Storage
 
to a non-valid\ different values 
result: the deploy are done successfully and the vm is deployed with another configuration - not the configuration according to the attributes specified.

by the way - you can leave those attributes empty and still , the deployment will be done successfully.

**Comment by nahumtimerman** [comment]
Boris, the issue with Dvswitch location / path not determining Network location has become clearer:
- if there is a network on the vcenter with the target name, the network will use existing rather than trying to create network with requested location... not a bug, but an expected behavior :(

**Comment by doppleware** [comment]
lets close
