### ISSUE TITLE
VM Location can't be empty - for deploying in the root

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#351]

**Comment by TomerAdmon** [comment]
If the user would like to deploy VMs to the root of the datacenter, he would think to leave the 'VM location' empty. in this case he will get an 'VM Location can't be empty' error.... 
options:
1) limitation - the solution pack can't deploy to the root
2) fix?

**Comment by alonagetzler** [comment]
i'm OK with having that as a limitation

**Comment by doppleware** [comment]
I'm okay with that limitation too.
Closing
