### ISSUE TITLE
An unclear notification appears when trying to deploy app from image

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#356]
STR 
Try to deploy a vm deployed from image app 

BIR
unclear error appears
![image](https://cloud.githubusercontent.com/assets/17527106/13552807/b23101a4-e379-11e5-8499-0dbf172102c6.png)

**Comment by razaba** [comment]
Lowered priority

**Comment by tornizanQ** [comment]
Still reproduce

**Comment by doppleware** [comment]
Please clarify the scenario so we can prioritize it

**Comment by tornizanQ** [comment]
Cannot reproduce
