### ISSUE TITLE
Error when deploying an app connected to a manual VLAN service

### ISSUE THREAD

**Issue by omerbotenski** [QualiSystems/vCenterShell#358]
STR:
1. Import the package "Route Attributes" located here: \\qsnas1\Shared\Omer\Bugs
2. Deploy both app one after the other
3. BIR if you get this error:

![image](https://cloud.githubusercontent.com/assets/17544324/13552971/1fe6c9d0-e380-11e5-976c-f2a2df942f86.png)

**Comment by TomerAdmon** [comment]
Verified
