### ISSUE TITLE
Not all "connect" actions apply when you perform them one after the other swiftly

### ISSUE THREAD

**Issue by omerbotenski** [QualiSystems/vCenterShell#361]
This is unstable. Try to connect and disconnect several routes in sequence.
Look at the attached gif

![connectdelay](https://cloud.githubusercontent.com/assets/17544324/13553873/2ad14db4-e3a0-11e5-879f-026580289b9a.gif)

**Comment by TomerAdmon** [comment]
cant reproduce....
