### ISSUE TITLE
Error when trying to deploy 2 apps from template connected by CVC

### ISSUE THREAD

**Issue by omerbotenski** [QualiSystems/vCenterShell#365]
Error when trying to deploy 2 apps from template connected by CVC.

Watch the attached gif.
This is unstable, but should be reproduced after 2-3 attempts.
![p21p](https://cloud.githubusercontent.com/assets/17544324/13554116/24570840-e3a8-11e5-994d-2b17416f393f.gif)

**Comment by alexazarh** [comment]
It happens because of a race condition.
We should have an internal discussion about this...

**Comment by alexazarh** [comment]
fixed

**Comment by TomerAdmon** [comment]
Duplicate #416 

Closing...
