### ISSUE TITLE
When connecting on VM to 2 other vm's and both connections have the same vnic request, the last connection overrides the first but it seems both configurations are applied.

### ISSUE THREAD

**Issue by omerbotenski** [QualiSystems/vCenterShell#370]
### Issue details

When connecting on VM to 2 other vm's and both connections have the same vnic request, the last connection overrides the first but it seems both configurations are applied.

![image](https://cloud.githubusercontent.com/assets/17544324/13554695/a760faa2-e3b7-11e5-9113-22d935926571.png)

### Steps to reproduce

1. Deploy 3 apps (A,B,C) from template
2. Create two CVC requests: 
A<->B
A<->C
3. Set the "Requested Source Vnic Name" attribute of both CVCs to "Network adapter 3" and connect both of them.

BIR if the last connection overrides the first but it seems both configurations are applied.

### Affected versions:

![image](https://cloud.githubusercontent.com/assets/17544324/13554709/1f675e06-e3b8-11e5-8131-1836d481a712.png)

CloudShell version  _Please fill in affected version_
![image](https://cloud.githubusercontent.com/assets/17544324/13554710/2af24b78-e3b8-11e5-92fd-73f836157314.png)

**Comment by TomerAdmon** [comment]
currently we got: 
![image](https://cloud.githubusercontent.com/assets/12639815/14061379/fa7fe18e-f38f-11e5-8ab6-f4101eb9b4eb.png)


Verified!
