### ISSUE TITLE
unable to deploy app from image \ template when connected via cvc to vlan \ app

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#372]
STR 
Have an reservation with deployed app from image \ template that is connected to vlan \ app
Run the deploy command
BIR
The app didn't deployed properly and an error appears:
![image](https://cloud.githubusercontent.com/assets/17527106/13554774/92126382-e3b9-11e5-9964-34739a2d530e.png)

**Comment by TomerAdmon** [comment]
fixed!
