### ISSUE TITLE
Vcenter Template input (in app "VM Deployment"): not supposed to include the DataCenter name

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#376]
Even when the “Default Datacenter” attribute in the Vcenter resource is exist (with value “QualiSB”), the Datacenter name is required in the "Vcenter Template" input inside app "VM Deployment"

![image](https://cloud.githubusercontent.com/assets/17528399/13555095/4fc52440-e3c0-11e5-80b6-da1e5274d82a.png)

**Comment by TomerAdmon** [comment]
Verified
