### ISSUE TITLE
Need to remove the attributes "Cloud provider", "VM_UUID"  from Deployed app family

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#383]
The attributes are not in use
i am not sure about the third attribute "Requested Vnic Name" -> consult with product

**Comment by alonagetzler** [comment]
All of those attributes shouldn't be associated with the deployed app model

**Comment by TomerAdmon** [comment]
@alonagetzler  - do we need the requested VNic on the family?
![image](https://cloud.githubusercontent.com/assets/12639815/13963040/6bf35cd2-f06c-11e5-8b3b-95af90388be5.png)

**Comment by tornizanQ** [comment]
@alonagetzler ?

**Comment by alonagetzler** [comment]
no
we just need to Requested vNIC attribute to be part of the package (not associated with any family/model)

**Comment by tornizanQ** [comment]
When deleting the "Requested vNIC" attribute from the "Deployed App" family the deployed app is fails to deploy with unclear error
