### ISSUE TITLE
When destroying a deployed vm that is connected to vlan the vlan is not erased from the db

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#388]
STR 
Have a reservation with deployed app connected to a vlan
Disconnect the vlan
destroy the app

BIR
The vlan is not erased from the db
but the connection is delted from the reservation

**Comment by razaba** [comment]
@tornizanQ 
do you mean the DB of cloudshell or vcenter?

**Comment by tornizanQ** [comment]
from cloudshell db
