### ISSUE TITLE
When trying to connect two vlans to a vm using the same Requested target vNIC Name the connection fail and an unclear error appears

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#394]
STR
Have a reservation with a deployed app in it connected to a vlan and the connection use the "Requested target vNIC Name " attribute
Add another vlan to the reservation
Connect the vlan to the deployed app using the Requested target vNIC Name with the same value as the previous connection 

BIR
the connection fail with an unclear error:
![image](https://cloud.githubusercontent.com/assets/17527106/13596314/6c2a93c6-e51a-11e5-8167-3816719d3188.png)

**Comment by razaba** [comment]
@tornizanQ 
please help me reproduce it... thanks

**Comment by tornizanQ** [comment]
verified
