### ISSUE TITLE
Save vNic information on route

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#40]
We should save the specific vNic used for a route on the route itself as an attribute. The attribute should be hidden to the end user

The attribute on the route should be called "Target Interface", it should be a string and associated with the rule "Link Configuration".

The value of this attribute will the name of the vNIC selected for this route.

motivation: know which vNIC to disconnect

**Comment by borismod** [comment]
@doppleware what is the family of the route? Should it be an attribute on the family or model?
