### ISSUE TITLE
App orchestration isn't running autoload if exsists on the deployed app

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#405]
Scenario: 
There is a driver on the deployed app family that contains autoload command. tha tuoaload will not be invoked automaticly during the app orchestration

**Comment by alexazarh** [comment]
@TomerAdmon  
Why is this a bug?
We never had a story about this...

**Comment by TomerAdmon** [comment]
@alonagetzler  -can we have a session about that?

**Comment by alonagetzler** [comment]
Expected behavior: If the deployed app has a driver with an Autoload command, this command should be executed after the deployment (and prior to the connectivity) in both the app orchestration script and in the environment Setup script.

**Comment by alexazarh** [comment]
There is no way to check if Autoload exist so we always try to execute Autoload.
Because of this I also added a bollean attribute called "Autoload", when the value is False the setup will not call the Autoload command.
