### ISSUE TITLE
Vcenter Template input (in app "VM Deployment") not supposed to be case sensitive

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#408]
STR:
1. open the manage page->Apps->"VM deployment" app -> try to insert the same name of the Vcenter Template but with uppercase (for example instead of "test" insert "TEST") 
BIR:
if the deployment is failed because it didn't find the template. it not supposed to be case sensitive, it supposed to find the template even when the name is in uppercase

![image](https://cloud.githubusercontent.com/assets/17528399/13634186/bbb451f6-e5fc-11e5-9175-204a77149aab.png)

**Comment by doppleware** [comment]
The vCenter API does require it to be case sensitive. 
So we're cancelling this one.
