### ISSUE TITLE
A success notification message appears when trying to establish a p2p connection between two undeployed apps

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#411]
STR:
1)have two undeployed apps 
2) connect between them

BIR:
there are two notifications - one is that the action can't be done (and it is ok) and the second one is that the routes connected successfully - which is wrong!

**Comment by Yairzeri** [comment]
![image](https://cloud.githubusercontent.com/assets/17525950/13635424/37a4fb6a-e604-11e5-8705-882ed9bdbb1b.png)

**Comment by alexazarh** [comment]
Can't reproduce - probably fixed on the way

**Comment by TomerAdmon** [comment]
@nahumtimerman  - Nahum, please verify

**Comment by TomerAdmon** [comment]
Verified
