### ISSUE TITLE
when connecting in parallel 2 P2P to the same VM -> both P2P are going to the same Nic (the last one win)

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#413]
STR:
1. have a reservation with 3 D.apps
2. add CVC request between D.App1 to D.App2 and between D.app1 to D.App3
3. then by using parallel tool connect both CVCs

BIR:
if just one Nic is configure in D.App1. 
Probably both Request send in the same time and both took the same Nic and then they configure the VM -> so the last one that configure the VM with the Vlan Wins :)

*** also happenes when doing it manual from portal (like try to connect 4 Vms to one VM, one by one)**
* similar to test case 151963
![connect in parallel 2 p2p](https://cloud.githubusercontent.com/assets/17528399/13668698/13a5283e-e6c7-11e5-888e-7ba003192ca6.gif)

**Comment by alonagetzler** [comment]
should throw an error

**Comment by yoavEkshtein** [comment]
verified on 179. 

it throws an error now
