### ISSUE TITLE
Wrong tooltip on the vlan id

### ISSUE THREAD

**Issue by Yairzeri** [QualiSystems/vCenterShell#417]

**Comment by Yairzeri** [comment]
![image](https://cloud.githubusercontent.com/assets/17525950/13669985/ca3a7d6c-e6cf-11e5-843b-bac118e3f3ea.png)

**Comment by alonagetzler** [comment]
should be 2-4094

**Comment by alonagetzler** [comment]
the attribute description should be 2-4094

**Comment by TomerAdmon** [comment]
Verified
