### ISSUE TITLE
Connectivity: can't connect between L2 port to L2 port

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#419]
related to test case 151909
STR:
1. have a reservation with 2 L2 mock up
2. then try to connect CVC between them 
BIR:
can't connect getting error msg (But i succeed to connect between L2 Port to D.App) - Maybe it is a bug in our L2 mockup driver... 

![image](https://cloud.githubusercontent.com/assets/17528399/13671674/ed9fad18-e6d9-11e5-95be-e02b6789aabd.png)

**Comment by TomerAdmon** [comment]
Verified
