### ISSUE TITLE
Connectivity: unable to connect between L2\DUT port to app

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#420]
related to test cases 150831, 151919
seems to be similar issue as #419

STR:
1. Have a reservation with app and L2 mockup and DUT that connected to L2
2. try to connect between the app to L2 port or to DUT port that have physical connection to L2 

BIR:
getting error msg - Maybe it is a bug in our L2 mockup driver... 
**will reprdouce also when connecting L2 port \ DUT(that connected to L2) to Vlan service
**
![image](https://cloud.githubusercontent.com/assets/17528399/13672580/223b5a78-e6de-11e5-9f13-73e40ca627b7.png)

**Comment by TomerAdmon** [comment]
verified
