### ISSUE TITLE
POD scenario: deploy app connected to 2 access vlans and one trunk vlan - the trunk vlan will not be configured

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#421]
after deploy VM all CVC's seeme connected:
![image](https://cloud.githubusercontent.com/assets/12639815/13677518/f2ed7638-e6f2-11e5-9213-dd79bf502816.png)

auto Vlan configured with range:
![image](https://cloud.githubusercontent.com/assets/12639815/13677524/f5ad60cc-e6f2-11e5-8658-918d68056d35.png)

result in Vcenter:
the trunk vlan is not configured
![image](https://cloud.githubusercontent.com/assets/12639815/13677525/f7ad8e92-e6f2-11e5-97bc-26fb60c8c420.png)

**Comment by TomerAdmon** [comment]
still doesn't work...

**Comment by razaba** [comment]
Could not reproduce with template : "Alex/test"

**Comment by TomerAdmon** [comment]
seems ok now.
