### ISSUE TITLE
write messages to output console

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#427]
The following messages should be shown in the output console:

[appName] deployment started
[deployedAppName] deployed successfully 

[deployedAppName] is powering on…
[deployedAppName] is powering off…

[deployedAppName] is being deleted…
[deployedAppName] was deleted

[deployedAppName] is waiting for IP address, this may take a while…
           --> show this for every minute that has passed
[deployedAppName] IP address is [IP_Address]
[deployedAppName] IP address not found

[deployedAppName] installation started
[deployedAppName] installation ended successfully

[deployedAppName] discovery started
           --> in case autoload exist in the deployed app
[deployedAppName] discovery ended successfully

**Comment by TomerAdmon** [comment]
Update: Logs will not be written if not during Setup, Teardown or app deployment
