### ISSUE TITLE
Automatic selection of the 1st available NIC

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#44]
what's available? we might want to get all the vNICs, see what they're connected to and decide accordingly. 

When connecting a route to a VM need to get all the connectors currently connected to the VM and select a NIC that isn't already used.

**Comment by alonagetzler** [comment]
We discussed the following logic.
Given that we receive a request to connect n vnics to n VLANs we take the following steps. 

1. For any connection request that also requires a specific vnic number (e.g '0').  If so check if that vnic is already added to the port group as requested, if not add it.
2. For connection requests that do not require a specific number:
    2.1. Find all vnics that already match the requests that are not already used for other existing requests (need to query the routes in the env), and use them to fulfill the new requests.
    2.2  For the remaining connections, first try and use those currently configured to the 'default' network (the one we assign to when we disconnect.
   2.3  For the remaining connections, can override any vnic as long as its not in use by an existing route in the environment
   2.4  If any connection still remaining, throw error

**Comment by yoavEkshtein** [comment]
should we add a force switch to let the user decide if the connection overrides exisiting connections?
