### ISSUE TITLE
Get unclear error when misconfigure app with vm cluster & resource pool that dont exist

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#451]
### Issue details

Get unclear error message when misconfigure app:
AttributeError: 'NoneType' object has no attribute 'resourcePool'

### Steps to reproduce

Configure app to override default VM Cluster & VM Resource pool.
Pass invalid values 

### Affected versions:
vCenterShell version  1.0.153

CloudShell version  Any

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by nahumtimerman** [comment]
enter a value for VM Cluster such that it is a path to a resource pool like this:
QualiSB Cluster\LiverPool

**Comment by TomerAdmon** [comment]
ssems ok to me.
