### ISSUE TITLE
Removing CVC that is partially connected NOT returning the Nic to the holding netwrok

### ISSUE THREAD

**Issue by DoronFried** [QualiSystems/vCenterShell#453]
STR:
1. have a reservation with D.app and a app
2. have a cvc between them and connect it
3. the route is "partially connected" and in state disconnected
4. remove the CVC

BIR:
if it not returning the Nic of the D.app to the holding network.

* we have a real issue here because the line is disconnected so the user cannot disconnect the CVC, he can just connect it or remove it. so i would expect that it will return the nic when doing remove to the CVC

**Comment by TomerAdmon** [comment]
#473 - duplicate

**Comment by TomerAdmon** [comment]
verified
