### ISSUE TITLE
Split vCetnter shell into small independent packages

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#457]
cloudshell.orch.core (pypi + git)

 -> connectivity
 - need to add to ES
 
VLAN.Connectivity (tfs + QualiPackage)
  - VLAN services
  - connect all script 
 
Apps (tfs + QualiPackage)
  - Applications category
  - App orchestration script.

CloudShell-Orch-Sandbox (git + QualiPackage)
 - requires specific version of orch. core
 - Package

vCenter Shell (git + pypi+ QualiPackage)
 - Deployment services
 - Pypi package
 - vCenter driver
 - Datamodel

**Comment by alexazarh** [comment]
@razaba 
We also need to remove the "environment_scripts" folder from the vCenter shell repo.

**Comment by alexazarh** [comment]
We also need to add server side tests for the packages that should be imported out of the box.
Please refer to "CloudShellScriptRunnerTestsScenario.cs" for an example how its done for "Cloud Shell Script Runner.zip"

**Comment by razaba** [comment]
added the necessary unit test

**Comment by tornizanQ** [comment]
Tested and passed successfully
