### ISSUE TITLE
Failed to delete (destroy) VM that is connected to vlan service in reservation

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#459]
[TeamServer.Service - Copy.txt](https://github.com/QualiSystems/vCenterShell/files/175863/TeamServer.Service.-.Copy.txt)
[QsRuntimeService.txt](https://github.com/QualiSystems/vCenterShell/files/175864/QsRuntimeService.txt)

Apps: Failed to delete (destroy) VM that is connected to vlan service in reservation
STR:
1. have a reservation with app and vlan that have a CVC request between them
2. deploy the app
3. then delete(destroy) the VM (D.App)
BIR:
getting error msg and the delete action failed.
*but in the second time you succeed to delete the VM 
 
logs are attached

**Comment by doppleware** [comment]
I think this was fixed by @alexazarh (server side fix)
@alexazarh , can you move to resolved?

**Comment by alexazarh** [comment]
Its actually both server side & python side fix.
Its resolved.

**Comment by TomerAdmon** [comment]
Verifeid!
