### ISSUE TITLE
Create a VLAN Auto service that uses the pool logic for VLAN allocation

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#46]
The attribute of this VLAN service should be:
- Allocation Ranges (=this attribute's value will be configured by the administrator)
- VLAN ID (user input)
- Interface VLAN Mode (user input)
- Virtual Network (=this attribute will hold the selected VLAN ID / range and won't be user input)
- Isolation Level (=default for this service is Exclusive, non user input)

**Comment by alexazarh** [comment]
Note:
Interface VLAN Mode attribute is called Access Mode

**Comment by alexazarh** [comment]
Do we want to set a default value for the Access Mode (Interface VLAN) attribute?

**Comment by alexazarh** [comment]
Note: The service owner id is currently the service name. Later it will be changed to be the reserved service id.

**Comment by alonagetzler** [comment]
Yes, we can set the default value to be "Access". Regarding the service owner ID - maybe create another issue so we won't forget to change it from the service name to the reserved service id.

**Comment by borismod** [comment]
@alexazarh, @alonagetzler Default was set to Access

**Comment by alexazarh** [comment]
I update the VLAN Auto service behavior:
1) Range request is not supported
2) If vlan id is empty than first available is selected from allocated ranges

**Comment by TomerAdmon** [comment]
part of the story were moved to :   #115
