### ISSUE TITLE
update a vlan-id doesn't works on AUTOVLAN service

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#464]
usability bug - 
As a user if I see the VLAN ID i expect that I can modify it.

![image](https://cloud.githubusercontent.com/assets/12639815/13811281/6fb4c908-eb7d-11e5-8e2a-dc85c1f45c31.png)

**Comment by TomerAdmon** [comment]
@alonagetzler - isn't it by design?

**Comment by alonagetzler** [comment]
indeed by design

**Comment by TomerAdmon** [comment]
Thanks, 
Closing....
