### ISSUE TITLE
When using deploy app from template an error returns

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#465]
STR
Have a reservation with an deploy app from template 
Run deploy app command 

BIR
an error appear - 

Error: CloudShellAPIError
Description: General Execution: Failed to start execution: Unexpected error - Python unhandled exception was raised while invoking server method 'LoadDriver' 'No module named shell.core.resource_driver_interface'. See the log file for more details.
[collection is empty]

if the virtual environment key is set on false, the deploy command is working correctly

**Comment by doppleware** [comment]
This was solved with 025f9e57f32530aea4b69f86932d2518fd63d977

**Comment by TomerAdmon** [comment]
fixed
