### ISSUE TITLE
Autoload fail with error if user is part of several domains

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#466]
### STR
1) Create another domain in the database
2) auto load

### result
you will get an error:
![image](https://cloud.githubusercontent.com/assets/12639815/13813951/f8c332ac-eb8c-11e5-86cf-13a9da8f1caa.png)

### how to fix:
please pass domain in this function instead of 'None'
![image](https://cloud.githubusercontent.com/assets/12639815/13813975/140035ba-eb8d-11e5-8732-f24fd75fd933.png)

### note!
please make sure we are passing the domain in all login requests....

**Comment by TomerAdmon** [comment]
@doppleware  - do we need to change it to be "Global" ?

**Comment by doppleware** [comment]
Yes. For our autoload, please change this to Global.

**Comment by TomerAdmon** [comment]
Verified
