### ISSUE TITLE
Add a "Refresh IP" command on a VM

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#47]
After a VM is deployed and powered On a "Refresh IP" command can be called to get back its IP and present it to the user and the deployed app's address.

The Refresh IP command should get the VM properties as input and set the IP as the deployed app's address.

This command should be associated with the vCenter

This command should be called as part of the App Deploy, after some delay time once the VM is powered on

**Comment by borismod** [comment]
@alonagetzler following our conversation, IP address should be obtained from the first network that is not the default network.
Default Network would be specified on an instance of "Generic Deployed App"  model

Retrieving IP address should be perform during timeout time, should be configurable.

Q: Where timeout will be stored? On the Vcenter of on the Deployed App? If on the deployed app, how it would be populated for new created apps?

**Comment by alonagetzler** [comment]
What do you mean by "specified on the deployed app instance"?

The timeout will be an attribute of the deployment service and therefore exposed to the user when creating the app. It will have a default value, and the value (default or user input) will be stored on the app instance itself, the same way we store the template selected by the app creator.

**Comment by borismod** [comment]
@alonagetzler "specified on an instance of "Generic Deployed App" model" is just a attribute on the VM. Ok, so the timeout would be also an attribute on the app.

**Comment by alonagetzler** [comment]
@borismod Just to clarify, the attribute of the "default network" should be associated with the vCenter resource and not with the Deployment Service.

**Comment by nahumtimerman** [comment]
Guys, refresh IP doesnt timeout nor is the discussed implementation available in Develop branch. (i guess the implementation is timeout attribute on vcenter resource?)

**Comment by nahumtimerman** [comment]
ok, I'll fix my comment, it does time out, but not configurable on vcenter resource
