### ISSUE TITLE
unstalbe: portal reservation delete apps - error message when trying to delete a deployed app

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#474]
to repro:

1. have a reservation with a deployed app
2. on the app , run the delete command

bir :

a user gets an error message

![image](https://cloud.githubusercontent.com/assets/12639815/13839652/58f5a41e-ec25-11e5-91a5-af6b140a1b30.png)

**Comment by alexazarh** [comment]
Duplicate of #459

**Comment by TomerAdmon** [comment]
Duplicate... closing...
