### ISSUE TITLE
deploy from image have 'VM Storage' default of 'datastore1'

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#477]
![image](https://cloud.githubusercontent.com/assets/12639815/13846385/585c876e-ec4f-11e5-9dc9-7feea3e21c68.png)

**Comment by doppleware** [comment]
@TomerAdmon I don't see anything like that in the data model, are you sure its not old data?

**Comment by TomerAdmon** [comment]
seems OK now
