### ISSUE TITLE
can't deploy from image if using a host inside a cluster

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#479]
STR;
1) autoload using "QualiSB/192.168.42.114"
2) deploy from image

![image](https://cloud.githubusercontent.com/assets/12639815/13846489/15f4d736-ec50-11e5-8616-3b048b665cba.png)

**Comment by doppleware** [comment]
@TomerAdmon  Can you specify which options to use during autoload?

**Comment by TomerAdmon** [comment]
Verified
