### ISSUE TITLE
Test task: Test support multiple connections between VMs and VLANs

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#48]
should be possible to connect a VM to multiple VLANs and a VLAN to multiple VMs

each connection should get its own NIC on the VM

connectivity JSON schema for bulk connect/disconnect request and response:
http://qs-srv-confluence:8090/display/QP/Connectivity+Schema

scenarios to check:
1. one reservation with a VM connected to multiple VLANs (3 VLANs to start with)
2. multiple concurrent reservations, each connecting VMs to the same VLAN
3. one reservation with a VLAN connected to multiple VMs (3 VMs to start with)
4. one reservation with a VLAN connected to multiple VMs and to a physical DUT

**Comment by alexazarh** [comment]
Can we close it?

**Comment by alonagetzler** [comment]
irrelevant now, cancelling
