### ISSUE TITLE
P2V: connection failed with no explanation

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#482]
### STR:
1) set "Tomer/dvSwitch2" as your dvSwitch
2) deploy a machine
3) add Vlan auto, choose VLAN id and connect

### Result:
![image](https://cloud.githubusercontent.com/assets/12639815/13848773/fa78dd48-ec5b-11e5-8f02-30a7fcae8c1e.png)

**Comment by TomerAdmon** [comment]
can be related to: #483

**Comment by TomerAdmon** [comment]
any problem in the Default dvSwitch will cause an error with no explanation to the user....

![image](https://cloud.githubusercontent.com/assets/12639815/13849845/7a23d026-ec60-11e5-8e9b-dd448f84ea83.png)

![image](https://cloud.githubusercontent.com/assets/12639815/13849854/7b6752d2-ec60-11e5-82bd-21a47d3ed1f7.png)

**Comment by razaba** [comment]
this is not a bug,
what happens:
Tomer/dvSwitch2 is not connected to a host, and more specifically not connected to the host that the vm is deployed on and vcenter can't connect the portgroup that we created on that dvSwitch to the vm.

the fix will be better error handling

**Comment by TomerAdmon** [comment]
Closing...
