### ISSUE TITLE
deploy from template doesn't use the requested resource pool

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#484]
### STR 
try to deploy from template to specific resourcepool

**Comment by razaba** [comment]
Not reproducible

**Comment by TomerAdmon** [comment]
STR:
1) set the "QualiSB Cluster" on the Vcenter resource and no resource pool
2) create an app and expose the resource pool to be a user input
3) set the resource pool to "Tor"
4) try to deploy the machine

result:
deployment failed with error:
![image](https://cloud.githubusercontent.com/assets/12639815/13914742/0c336c9c-ef59-11e5-8ca4-58dda472f802.png)

**Comment by TomerAdmon** [comment]
Verified
