### ISSUE TITLE
can't deploy from template when using specific storage that located under a DRS

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#485]
## STR
try to deploy from template using: "eric ds cluster/datastore1 (1)"

![image](https://cloud.githubusercontent.com/assets/12639815/13849417/bdf14100-ec5e-11e5-8923-7d2de62c1b38.png)

**Comment by doppleware** [comment]
Lets investigate, maybe related to the naming special characters?

**Comment by TomerAdmon** [comment]
seems like when you have a cluster storage you cannot choose specific datastore inside it in the Vcenter GUI, same as for the api. the behavior in out VcenterShell seems like when you choose a storage under a DRS, you will actually deploy it to the DRS
