### ISSUE TITLE
Connections that failed on both endpoints still grab vlan from pool and hold it exclusively

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#498]
### Issue details

Even if connection fails on both sides, vlan item is added to table in isolation level=0 (exclusive)
If there is a limited allocation range on default vlan, you won't be able to use vlan till connection has been removed or reservation ended

### Steps to reproduce

Even if connection fails on both sides, vlan item is added to table in isolation level=0 (exclusive)
If there is a limited allocation range on default vlan, you won't be able to use vlan till connection has been removed or reservation ended

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by doppleware** [comment]
by design
