### ISSUE TITLE
Add connector status to GetReservationDetails XML output

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#503]
we need to return information about the connection status in GetReservationDetails - add a new field for connector with the following optional values:
- (empty) --> regular visual connector
- Connected
- Disconnected
- Partially Connected
- Failed
- Connecting
- Disconnecting

**Comment by TomerAdmon** [comment]
@DoronFried

**Comment by alexazarh** [comment]
Added a field called "State"
