### ISSUE TITLE
Cannot "Delete" command on app resource if underlying VM no longer exists in vcenter

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#505]
### Issue details

Cannot use "delete" command on  app resource if underlying VM no longer exists in vcenter

### Steps to reproduce

Deploy an app successfully.
As an admin, clean a folder from VMs in vcenter because you ran out of storage.
Now run "delete" command on deployed app

Delete will fail and NOT delete deployed app even though its underlying VM no longer exists

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by nahumtimerman** [comment]
error: 
RESERVATION
Delete ended with status Failed with error: 'NoneType' object has no attribute 'runtime'

**Comment by alexazarh** [comment]
@alonagetzler Do we want to leave this as is or delete the cloudshell resource even if the vm doesnt exist anymore?

**Comment by alonagetzler** [comment]
delete the cloudshell resource if the VM doesnt exist anymore
