### ISSUE TITLE
cannot deploy from image with --quiet tag

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#508]
### Issue details

cannot deploy from image with --quiet tag 

### Steps to reproduce

1. deploy from OVF
2. add to the arguments : --quiet
3. deploy

### Affected versions:
vCenterShell version  0.166
CloudShell version  7.0.7641

![image](https://cloud.githubusercontent.com/assets/16865064/13905561/fb193d84-eecb-11e5-904a-3d05893905ae.png)

**Comment by alexazarh** [comment]
@alonagetzler 
Do we need to support this?
