### ISSUE TITLE
Error throw when try to connect more than one subresource of deployed app to same vlan at once

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#512]
### Issue details

Error throw when try to connect more than one subresource of deployed app to same vlan service at once

### Steps to reproduce

Have deployed app with 2 child connectable ports.
Add CVC to resolved vlan, using Save & Connect for two routes at once.

Error is reproduced if both CVCs are in failed state, get "sequence contains more than one matching element", and vlan is still configured on on VM (but will not be cleaned when performing disconnect / remove route)

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by alexazarh** [comment]
The returned json from the vCenter driver contains a duplicate action id

**Comment by TomerAdmon** [comment]
seems fixed.
