### ISSUE TITLE
wait for IP boolean input set to false - still waiting for IP

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#519]
if the "wait for IP" boolean input is set to "false" - deployment still waits for IP

### Steps to reproduce

1. have an app to deploy from template
2. set the wait for IP to false
3. deploy

result : still waiting for IP. if none recieved , timeout after 10 minutes

### Affected versions:
 
3049

### Affected platforms

**Comment by doppleware** [comment]
By design - it was decided that the auto events only setup
