### ISSUE TITLE
Can't override vlan using target vnic [Not sure if bug or I misinterpret product design]

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#524]
### Issue details

Get error when try to override generated vlan using dragging CVC with target vnic name

### Steps to reproduce

have a deployed app with p2p connection to Network adapter 2
add manual vlan, connecto to deployed app, while setting target vnic name="Network adapter 2"
hit connect

seems like according to this issue it should be able to override the existing network:
https://github.com/QualiSystems/vCenterShell/issues/44

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by doppleware** [comment]
It shouldn't overrde

**Comment by nahumtimerman** [comment]
Email from Alona & Raz:
It use to throw exception but we decided to change it to override it

From: Alona Getzler 
Sent: Tuesday, March 22, 2016 9:37 AM
To: Nahum Timerman <Nahum.T@quali.com>
Cc: Raz Abadi <Raz.A@quali.com>
Subject: RE: requested target vnic name

If I remember correctly, I think it should override the existing network on the vNIC


its also specified as a test case...
are you *sure* that it throws an error?

**Comment by nahumtimerman** [comment]
@alonagetzler please confirm or close

**Comment by alonagetzler** [comment]
in this scenario we shouldn't override but throw an error, so no bug
