### ISSUE TITLE
A non-qs-generated portgroup is overwritten before holding network

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#525]
### Issue details

a non-qs, non-holding network is overwritten before an available holding network

### Steps to reproduce

Have a deployed app with 4 nics:
networks on nics - vlan 73, holding, holding, holding
vlan 73 is on a dvswitch called production and isnt the default dvswitch.

connect 2 peer to peer connections to your deployed app.
now connect a manual vlan to it

defect is reproduced if vlan 73 is overwritten before the available holding network

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by alexazarh** [comment]
still reproduces
