### ISSUE TITLE
Make "Requested Target vNic name" & "Requested Source vNic name" case insensitive

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#526]
### Issue details

Make "Requested Target vNic name" & "Requested Source vNic name" case insensitive

### Steps to reproduce

When i enter "Network Adapter 1" & "Network adapter 1" in target vnic name, I mean the same thing

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by doppleware** [comment]
Not possible for us since vCenter's API is

**Comment by alexazarh** [comment]
Cancelling this bug
