### ISSUE TITLE
Autoload in setup writes to reservation output even if no app has Autoload == true

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#527]
### Issue details

While executing setup, "<deployedappname> discovery started" is always written to reservation output, even if deployment option has Autoload==false setting

### Steps to reproduce
Have an environment with a single reserved app, that has Autoload set to false, and no driver.
make sure the environment has the setup script + driver
reserve the environment

defect is reproduced if still get this message:
message='[{0}] discovery started'.format(deployed_app_name)

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by alexazarh** [comment]
Fixed along the way
