### ISSUE TITLE
Setup script: if there is an error during autoload, don't get error in activity feed / reservation output

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#529]
### Issue details

Setup script: if there is an error during autoload, don't get error in activity feed / reservation output

### Steps to reproduce

Have an environment that should call autoload on reserved app during setup
run setup

defect is reproduced if neither activity feed or reservation output indicates that autoload failed during execution

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by TomerAdmon** [comment]
Verified 
![image](https://cloud.githubusercontent.com/assets/12639815/14081171/0b9838c6-f512-11e5-8c0a-a372d07fcb56.png)

![image](https://cloud.githubusercontent.com/assets/12639815/14081178/15453b6c-f512-11e5-9c2e-6cb6af08933b.png)
