### ISSUE TITLE
Vnics definition being ignored by setup script

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#531]
STR
Have an environment with setup and teardown scripts 
Add two vlan connected and one app 
Connect the vlans to the app
Give each cvc different vnic on the app 
Reserve the environment

![image](https://cloud.githubusercontent.com/assets/17527106/13951270/6f9594a6-f038-11e5-9836-e8eef25cd043.png)

BIR
Option 1:
The setup is finishd with active with error statue and in the activity log an error will apear with the message that the vnic is not exist, the cvc will connect manually after the setup is fail

Logs (Bug is reproduced on 22.03.2016 14:11):
[Logs1413.zip](https://github.com/QualiSystems/vCenterShell/files/184058/Logs1413.zip)

Option 2:
Setup will ignore the vnics definition

Template
Tor/Tiny Tor

Vcenter on 192.168.42.110

**Comment by razaba** [comment]
@doppleware 
finished all the logics,  commited and ,merged to the develop

**Comment by razaba** [comment]
moving to write unittests

**Comment by tornizanQ** [comment]
Verified on 7.0.0.8081
