### ISSUE TITLE
P2P with specific source and target will fail during deployment (deploy apps manually)

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#532]
### STR

1)	Connect two apps to each other (each template have 4 Nics)

 
![image](https://cloud.githubusercontent.com/assets/12639815/13951286/883e0100-f038-11e5-8915-b7af66c53308.png)

2)	Choose specific Nics (source – Network adapter 4, target – Network adapter 2)
 
![image](https://cloud.githubusercontent.com/assets/12639815/13951289/89f469a8-f038-11e5-98cc-01bff95d5af6.png)

3)	Deploy both app

###result:
![image](https://cloud.githubusercontent.com/assets/12639815/13951290/8d147452-f038-11e5-8e79-81b6c5b8961a.png)

One machine completed the deployment, one not
![image](https://cloud.githubusercontent.com/assets/12639815/13951295/900b86be-f038-11e5-9d0d-0cdc265feba5.png)

Server logs:
2016-03-22 14:12:09,923 [55] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TOMERAD:8029 - Tcl, QualiSystems Username: admin]
Photon1_94752b9c: 'get_inventory' command failed with 'TypeError' error.
Description: expected string or buffer
2016-03-22 14:12:09,948 [53] ERROR ResourceManager.TclAPI - [IP: ::1, Machine: QS-IL-TOMERAD:8029 - Tcl, QualiSystems Username: admin]
Photon_e354dcf6: 'get_inventory' command failed with 'TypeError' error.
Description: expected string or buffer

**Comment by alexazarh** [comment]
Cant reproduce

**Comment by TomerAdmon** [comment]
Closing - opened as bug for Shays scrum after repreduced with Alex.Az - http://team:8080/tfs/Quali-Collection/QualiSystems/_workitems#_a=edit&id=152465
