### ISSUE TITLE
When having an environment with only deployed apps and no undeployed apps the setup is not seems to run

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#535]
STR
Have a reservation with setup script
Add two vms to the evironment 
connect the vms via cvc
Reserve the environment 

![image](https://cloud.githubusercontent.com/assets/17527106/13954020/a31a60cc-f047-11e5-90ae-9d9fca73875c.png)

BIR
The connection is not established and the reservation is active with out an error

Logs, Bug reproduced on 22.3.16 15:58
[Logs1558.zip](https://github.com/QualiSystems/vCenterShell/files/184225/Logs1558.zip)

**Comment by TomerAdmon** [comment]
bug is partially resolved. the setup wil start and connect the machines, but if the machine was already powered on in the vcenter the setup will fail with error:

### STR
1) have and environment with Setup & Teardown
2) add two machines that are already exist in the vcenter and they are powered on
3) reserve

### Result:
setup fail with error
![image](https://cloud.githubusercontent.com/assets/12639815/14061562/f4463ff8-f393-11e5-877a-5678212d0b73.png)

**Comment by tornizanQ** [comment]
verified
