### ISSUE TITLE
Side by Side compatibility - Vlan ID attribute causes BM package to be unimportable

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#536]
if the old (2.1.0.19) virtualization package is installed , there is already an attribute called "VLAN ID"
the BM package tries to import "VLAN Id" and fails.

### Steps to reproduce

1. import the v2 vlan package
2. try to import vcentershell.zip

result: can't , due to reason mentioned above

**Comment by doppleware** [comment]
Hi,
Please change (in blue mountain) to "VLAN ID" (Capital 'D')

**Comment by yoavEkshtein** [comment]
verified on 1.0.183
