### ISSUE TITLE
Side by Side compatibility - cloud Provider family causes BM package to be unimportable

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#537]
### Issue details

old v2 Virtualization package contains "cloud provider" family that is a mappable container
trying to import BM will include a cloud provider family that is not a mappable container , thus failing the import

### Steps to reproduce

1. import old v2. Virtualization package
2. import the BM package

result:
import will fail because of the reason mentioned above

**Comment by doppleware** [comment]
Please assign to Alona to add to install instructions and close.

**Comment by alexazarh** [comment]
@alonagetzler 
Is this still happening or its fixed already?

**Comment by alonagetzler** [comment]
we need to have an SQL query ready to fix databases that have the old virtualization package (remove the "mappable container" property frmo the Cloud Provider family)

**Comment by alexazarh** [comment]
This should work:
  Update ResourceFamily 
  Set IsMappableContainer = 0
  Where Name = 'Cloud Provider'

**Comment by alexazarh** [comment]
Another error that might happen is: 
"Orchestration service already exists: 'Orchestration'"

We have 2 options to solve this:
1)	Remove this service family using RM
2)	Run the following query to change the family type to Regular if you don’t want to remove it:
  Update ResourceFamily 
  Set ServiceType = 1
  Where Name = 'Orchestration'
