### ISSUE TITLE
No indication that autoload fails or why it fails when running deploy app

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#539]
### Issue details

No indication that autoload fails or why it fails when running deploy app

### Steps to reproduce

No indication that autoload fails or why it fails when running deploy app

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by TomerAdmon** [comment]
@alonagetzler Seems like now we have an entry in the activity feed, but the orchestration isn't failing when there is an error.... is it OK?

**Comment by alonagetzler** [comment]
@TomerAdmon  I think the orchestration should fail in this scenario

**Comment by TomerAdmon** [comment]
@alexazarh  - reopen

**Comment by TomerAdmon** [comment]
Verified
