### ISSUE TITLE
autoload will always fail on deployed app

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#541]
### Issue details

autoload will always fail on deployed app

### Steps to reproduce

deployed app initially gets the address "N\A"
Autoload uses separator to parse the relative path of resources, so this separator in root address messes up the autoload and causes it to always fail.

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by doppleware** [comment]
Changed default addres sto 'NA'

**Comment by nahumtimerman** [comment]
Fixes it, thanks
