### ISSUE TITLE
Vlan form has some unclear design

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#544]
STR
Have a reservation 
Add Auto vlan to the reservation

BIR
Observe the service detail window that opened

![image](https://cloud.githubusercontent.com/assets/17527106/13977768/7320cc98-f0d4-11e5-8d23-ddf50b6bcfa1.png)

The virtual network have a visual text box but is not editable while the vlan ID is editable but the textbox is not shown if the mouse is not over it

**Comment by alonagetzler** [comment]
please open this bug in TFS and cancel this one
