### ISSUE TITLE
Connecting two manual vlan to the same VM cannot be disconnected when removing one of the vlan

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#545]
STR
Have a reservation with a deployed vm with at least two vnics 
Add two manual vlan and config them both to the same ID
Connect one of the vlans to the resource
After the connection is established, change the vlan alias
Connect the other vlan
after the connection as been established, delete the previous vlan with the changed alias

![image](https://cloud.githubusercontent.com/assets/17527106/13978258/603d7208-f0d8-11e5-979e-1e28a6f00d81.png)

BIR
1) The vlan is not disconnected and the port is still connected to the vm

2) if the user tries to disconnect the vlan instead it will finish with disconnection fail message and if he will try to reconnect it after it fails  to dissconect, the user wont be able to disconnect the vlan again or to remove the vlan or even end the reservation.

Logs to the first scenario 23.3.16 09:20
[Logs0920.zip](https://github.com/QualiSystems/vCenterShell/files/185527/Logs0920.zip)

**Comment by alonagetzler** [comment]
lowering priority as this isn't a main use case (having two VLAN services with the same ID)

**Comment by alonagetzler** [comment]
no need to fix that
