### ISSUE TITLE
If a machine fail to load during setup, the other vms also will fail to load correctly

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#546]
STR
Have an environment with setup command 
Add three apps to the reservation 
Change one of the apps template location to an invalid template
Reserve the environment 

BIR
The setup finish with active with error statue and both of the other apps stopped in the middle of the installation process

Environment package:
[Environment-3-23-2016 12-17.zip](https://github.com/QualiSystems/vCenterShell/files/185801/Environment-3-23-2016.12-17.zip)

Logs bug reproduced on 23.3.16 12:37
[1238.zip](https://github.com/QualiSystems/vCenterShell/files/185800/1238.zip)

**Comment by doppleware** [comment]
by design
