### ISSUE TITLE
Ending a reservation with teardown completes and some vms survive the process

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#547]
STR
Have a reservation with teardown script attached and 10 deployed apps with some random connection between them 
End the reservation 

BIR
The reservation is with status completed, but there are still some apps in it
![image](https://cloud.githubusercontent.com/assets/17527106/13984796/33a1e25a-f101-11e5-9fd7-a4bbc07b93e3.png)

Environment package:
[Uploading withSetandTear2.zip…]()

Logs 23.3.16 13:40
[Terminate1340.zip](https://github.com/QualiSystems/vCenterShell/files/185928/Terminate1340.zip)

**unstable

**Comment by alexazarh** [comment]
This error is caused because of a deadlock. Asked Shay Keren to take a look.

**Comment by alexazarh** [comment]
@tornizanQ 
according to shay the deadlock issue fixed in the trunk

**Comment by tornizanQ** [comment]
cannot reproduce
