### ISSUE TITLE
[Server Error] Concurrent calls to "Delete" resource command on vcenter can run into a NHibernate.ObjectNotFoundException

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#548]
### Issue details

[Server Error] Concurrent calls to "Delete" resource command on vcenter can run into a NHibernate.ObjectNotFoundException

### Steps to reproduce

Have a reservation with ~15 deployed apps that also autoloaded ports.
This reservation should have the default sandbox teardown.
run teardown.
Many "delete" commands on the vcenter will fail with a server error.

The associated server bug is:
http://team:8080/tfs/web/wi.aspx?pcguid=7f0f1432-0cbe-43ca-b805-7a63763a5206&id=152483

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by borismod** [comment]
@QualiSystems/vcentershell It looks so nice when people use github templates :+1: 
//cc @nahumtimerman

**Comment by nahumtimerman** [comment]
:)

**Comment by doppleware** [comment]
should be fixed with latest server changes
