### ISSUE TITLE
if connection takes a few seconds , the dialouge window does not close and confuses user

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#549]
### Issue details

if there is a connection (let's say , DUT <--> app) that takes a few seconds to connect , the dialouge windows stays open , and it is difficult to the user to understand if something is happening.

### Steps to reproduce

1. have a connection that will take a few seconds to connect ( such as app to mock l2's DUT)
2. connect through the dialouge a DUT port to an app (add , then click "save and connect")

nothing happens.
there will be a few awkward seconds in which you wouldn't know if you clicked or not .

then , the connection will be made and the dialouge window closed.

### Affected versions:
vCenterShell version  1.0.172

CS version: 7.0.0.7491

**Comment by alexazarh** [comment]
Please open this bug for Shay's scrum
