### ISSUE TITLE
Remove connected app will disconnect CVCs one by one and not as bulk

### ISSUE THREAD

**Issue by TomerAdmon** [QualiSystems/vCenterShell#554]
### Issue details
![removevm](https://cloud.githubusercontent.com/assets/12639815/14012347/e6a391da-f1ad-11e5-8b1b-74f0f7b89d36.gif)

### Steps to reproduce

1) Have an app connected to 2 Vlan services
2) remove the resource

### Result
 CVCs are disconnecting one by one and not as bulk

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by alexazarh** [comment]
Please open a bug to Shay's team to raise an event for removed visual connector one time with multiple visual connectors, instead of raising one event for each connector

**Comment by TomerAdmon** [comment]
known limitation.... remove the new and move to backlog (after talking to @doppleware )
