### ISSUE TITLE
if a vlan has recieved an ID , there is no way to change it

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#557]
### Issue details

if a vlan has recieved an ID (or a range of ids) , there is no way to change it

### Steps to reproduce

1. have a vlan service, set a specific vlan ID or range for it
2. connect the vlan to an app so the vlan would be set.
3. disconnect or remove the connection
4. change the id or range for the vlan
5. try connecting again

result - the selected vlan will be the original vlan set in step 2 , regardless of other performed steps

### Affected versions:
vCenterShell version  176

**Comment by alexazarh** [comment]
This is the wanted behavior. If a vlan service was resolved the id cant be changed.
