### ISSUE TITLE
if a vlan recieves a "broken" vlan ID , the vlan is chosen from allocation range

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#561]
### Issue details

an invalid or broken vlan ID results in vlan choosing from "next available" instead of invoking an error

### Steps to reproduce

1. add a new vlan. 
2. in the "vlan ID" field , write something that is not valid , like "5,8" or "I want a vlan"
3. connect to a vm

result: instead of an error , behaviour is to choose "next available" from allocation range

### Affected versions:
vCenterShell version  176

**Comment by alexazarh** [comment]
Duplicate of #292
