### ISSUE TITLE
vlan allocation range does not accept broken ranges as input

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#562]
### Issue details

_Please provide issue details here_.
![image](https://cloud.githubusercontent.com/assets/16865064/14064618/199cc5d2-f412-11e5-9c3d-29924c361259.png)

### Steps to reproduce

1. add a vlan with a broken range allocation range ( like 100-500 , 600-800)
2. try to get a vlan from the second range (i.e 681)

result - since it is not in the first range , it will fail.

### Affected versions:

vCenterShell version  176

**Comment by doppleware** [comment]
check if duplicate with #561

**Comment by alexazarh** [comment]
too risky at the moment

**Comment by GilGald** [comment]
if the range is 5-1 it will swap the value to be 1-5
