### ISSUE TITLE
When changing vcenter properties wrong error is displayed

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#567]
STR
Change the vcenter dvswitch attribute to a non existing dvswitch name
save the changes 
Create a reservation 
Add a app to the reservation
Connect the app to a vlan 
Deploy the app 

BIR 

A non clear error is appeared
When using non existing dvswitch
![image](https://cloud.githubusercontent.com/assets/17527106/14065793/82c22b5a-f440-11e5-8e00-36235f7b4042.png)

**Comment by alexazarh** [comment]
@tornizanQ 
Can you please confirm that you can reproduce this bug?

**Comment by tornizanQ** [comment]
Still reproduce

**Comment by tornizanQ** [comment]
The error message is different but still not clear 

![image](https://cloud.githubusercontent.com/assets/17527106/14784552/df6f9df4-0afe-11e6-9194-02399647a93f.png)
