### ISSUE TITLE
notification error is not clear when using wrong user name or password

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#568]
STR
have a vcenter that is point on avcenter but with wrong user name or password
Create a reservation 
Add a app
Deploy the app

BIR
not clear error is appear

![image](https://cloud.githubusercontent.com/assets/17527106/14065842/f50518ac-f441-11e5-8f62-71a81cd1e2f7.png)

**Comment by TomerAdmon** [comment]
Verified: 
![image](https://cloud.githubusercontent.com/assets/12639815/14081075/6eafcfa6-f511-11e5-936d-aa5fc74c907a.png)
