### ISSUE TITLE
Error on setup script that has CVCs with physical endpoint

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#570]
### Issue details

Environments with setup script, and CVCs with a physical endpoint (DUT linked to L2) 
don't get activated

### Steps to reproduce

Have an environment with DUT that is connected to L2 (typical enviornment attached)
environment should have setup script
reserve the environment

defect is reproduced if fail to connect CVCs with dut endpoints because resource is not found

### Affected versions:
vCenterShell version  _Please fill in affected version_

CloudShell version  _Please fill in affected version_

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by TomerAdmon** [comment]
connection works (failing on refresh ip  - another issue)
