### ISSUE TITLE
When running teardown dissconecting app returns an error that not connection has been found

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#587]
STR
Have a reservation with teardown script 
Add two deployed apps to the reservation
connect the vms 
end reservation
BIR
the vms are being disconnected before the reservation enters teardown and the console output returns :
Disconnecting all apps...Error disconnecting apps. Error: Didn't find any connected connectors. Nothing to disconnect.Apps are being powered off and deleted..

Logs
[Uploading 1840.zip…]()

**Comment by tornizanQ** [comment]
Following a conversation with Alex we understood we need some direction about how it should work 
the disconnect  should run in the end reservation
or 
in the teardown itself

**Comment by alonagetzler** [comment]
The CVC disconnect should happen in the “end reservation” itself, not in the teardown!

**Comment by tornizanQ** [comment]
verified
