### ISSUE TITLE
Create app orchestration

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#59]
http://team:8080/tfs/Quali-Collection/QualiSystems/_workitems/edit/128989

**Comment by alexazarh** [comment]
Step #2 (execute Connect) is still missing

**Comment by alexazarh** [comment]
Connect is now part of the orchestration process

**Comment by alexazarh** [comment]
Need to add the execution of the installation dynamically.

**Comment by alexazarh** [comment]
fixed installation
