### ISSUE TITLE
When autoload is missing an error notification appears

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#592]
STR
Have a cloudshell environment with an app while autoload is missing 
reserve the environment 
deploy the app 

BIR
An error appears
![image](https://cloud.githubusercontent.com/assets/17527106/14100232/a64abf1a-f594-11e5-8c6b-5489f310d5d7.png)

**Comment by TomerAdmon** [comment]
I think it happens when there is no driver at all on the deployed app....
