### ISSUE TITLE
Console output should not display the log file handler line

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#593]
str
run a setup script in a environment with deploy app
BIR
in the console there is a line about log position that shouldn't be there
![image](https://cloud.githubusercontent.com/assets/17527106/14102318/819c8d70-f5a2-11e5-8f25-838cf3ce4fbf.png)

**Comment by borismod** [comment]
This line is written by the logger infrastructure and I find it quite useful. It tells where the log file is located. Please consult with @alonagetzler and @eigel

**Comment by alexazarh** [comment]
We need to remove this. It shouldnt be in the output :)
@alonagetzler agrees with this statement...

**Comment by doppleware** [comment]
I already fixed this we just need to update cloudshell.core in the ES

**Comment by tornizanQ** [comment]
it is still there, is there something that I am missing?
