### ISSUE TITLE
connect all : if one of the connections cannot be made, error is very long and not clear

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#598]
### Steps to reproduce

1. have a vm with a few vnics
2. have all  vnics already connected
3. connect a vlan to the vm and to another vm (with free vnics that time)

result:
it should fail , but with clearer error

this is the error:

![image](https://cloud.githubusercontent.com/assets/16865064/14108502/70338b28-f5c6-11e5-9021-c1f8151f2026.png)

### Affected versions:
vCenterShell version  192

**Comment by yoavEkshtein** [comment]
logs added.

extension should be changed to .zip before opening
[logs.pdf](https://github.com/QualiSystems/vCenterShell/files/193535/logs.pdf)

**Comment by alexazarh** [comment]
"Connect All" is currently a python script.
Need to  convert it to python driver to be able to have clear messages
