### ISSUE TITLE
soft shutdown fails if vmware tools is not yet running

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#608]
### Issue details

if a soft shutdown is attempted and vmware tools are not running the soft shutdown will fail. 
the indication to the user is less than helpful , and the user has no indication from CS to see if the tools are running or not.

error recieved:
![image](https://cloud.githubusercontent.com/assets/16865064/14139007/1536574c-f679-11e5-8a16-a2c96be3d6e6.png)

### Steps to reproduce

1. turn on an app
2. promptly and softly , shut down the app

result : 
the error mentioned above

### Affected versions:
vCenterShell version  193

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by alexazarh** [comment]
Need to throw a better error message
