### ISSUE TITLE
Generate public documentation

### ISSUE THREAD

**Issue by borismod** [QualiSystems/vCenterShell#61]
As a user I would like to be able to read documentation of vCenterShell classes and methods.

Directions for investigation:
http://sphinx-doc.org/
https://github.com/integrations/gitbook

Acceptance criteria:
1. Documentation generated as part of CI and published on github
2. Generated documentation is versioned and accessible from github by version

**Comment by Costya-Y** [comment]
Will be added to a 2nd Gen Shell
