### ISSUE TITLE
Running a setup on enviorment with 42 apps on it does not end even after an hour

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#610]
STR
have an environment with setup script 
add 42 apps
reserve the environment 

BIR
after an hour the setup is still running but its seems that some apps are stopped from deployment without any error 

If I try to deploy them manually they are deployed without a problem

Logs
[40appsres.zip](https://github.com/QualiSystems/vCenterShell/files/195946/40appsres.zip)

pics
![image](https://cloud.githubusercontent.com/assets/17527106/14149300/2c1575a0-f6ac-11e5-9b9b-a25740bf1028.png)

**Comment by razaba** [comment]
http://team:8080/tfs/Quali-Collection/QualiSystems/_workitems#_a=edit&id=152745
