### ISSUE TITLE
in a teardown of a few vms, some were not deleted

### ISSUE THREAD

**Issue by yoavEkshtein** [QualiSystems/vCenterShell#611]
### Issue details

the reservation has 8 vms that were deployed successfully in setup , but failed during teardown

log (zip , not actually pdf):
[4a23f46d-fee2-4376-a11c-1ab2ea098d7c.pdf](https://github.com/QualiSystems/vCenterShell/files/196015/4a23f46d-fee2-4376-a11c-1ab2ea098d7c.pdf)

### Steps to reproduce

This has happened once , this is the environment used:

![image](https://cloud.githubusercontent.com/assets/16865064/14150469/cdf06376-f6b1-11e5-924e-a160ec7a8d26.png)

### Affected versions:
vCenterShell version  194

### Affected platforms

- [ ] Virtual Environment

_Please fill additional environment specific configuration_

**Comment by alexazarh** [comment]
Can you also provide the vCenter driver logs?

**Comment by doppleware** [comment]
I'm raising this to P1 as it also connects to other issues we've been seeing with large number of VMs.
Please do testing + bulletproofing of flows with 50 VMs

**Comment by doppleware** [comment]
Also check #610

**Comment by alexazarh** [comment]
Not reproduced. It was caused because of a bug in reservation that was already resolved
