### ISSUE TITLE
Add auto-events support to orchestration

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#620]
the following auto events on an app should be used also when deploying a single app and not just via the setup:
auto power on, refresh IP, autoload

user flow to test - (1) make the above attributes user inputs for a deployment option, (2) create an app and change the default values of those auto events, (3) add the app to a reservation, (4) run the "Deploy" command --> the auto events new values should be used

need special logic when auto power on is False, app orchestration shouldn't call refresh IP and install (same as Setup)

**Comment by tornizanQ** [comment]
http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=153656
