### ISSUE TITLE
Expand Resource to contain data about its creators

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/vCenterShell#640]
Lets implement the following behavior:
1. Add three new properties to any resource: created_by_user, created_by_reservation and created_by_domain. These values should be taken from the active execution instance when the resource was created. If the resource was created in a reservation, we need to take that info from the reservation (owner, domain, reservation_id)
1b. Get reservation details should return these details as well in the resource xml (not the matrix in studio etc.)
2. Ask Assaf to add these fields to elastic
3. The teardown procedure should only delete/power off VMs that were created in that sandbox.
4. Change lock by default to true for generic deployed app.
5. Try to bribe Liron to add a checkbox to filter this in the resource search pane... (talk to Meni)

**Comment by alonagetzler** [comment]
implemented by Shay's team
