### ISSUE TITLE
When refreshing the page in the middle of filling the vmWare vCenter resource template the resource is created even if some of the properties are missing

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#644]
STR
Go to Inventory and Add new resource
Select the VMware vCenter Shell
Enter a name and IP
Click create
The Resource Discovery Information form is opened 
Refresh the page

BIR
The new resource is created and included even with the missing parameters

**Comment by alexazarh** [comment]
@tornizanQ 
Please open this bug to the scrum team that is responsible for the resource template screen. I think it's Shays scrum...

**Comment by tornizanQ** [comment]
The Bug on TFS
http://team:8080/tfs/web/wi.aspx?pcguid=7f0f1432-0cbe-43ca-b805-7a63763a5206&id=152884
