### ISSUE TITLE
Split packages.zip to multiple files in the same folder

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/vCenterShell#650]
Split packages.zip to multiple files in the same folder so that all the packages that are in this folder will be imported. 

Notes:
1) Need to save the last modified data of each package in order to know if its a new package we need to import
2) Need to verify that it works in case of migration from 7.0 EA to 7.0 GA

**Comment by alexazarh** [comment]
merged to 7.0

**Comment by tornizanQ** [comment]
Waiting for bug #677
