### ISSUE TITLE
Trying to deploy a VM with wrong vcenter address ends with wrong fail message

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#662]
STR
Have a reservation 
Change the vCenter resource address to a wrong IP address 
add a deploy from template / clone / image / link app 
Run deploy command 

BIR 
an unclear fail message appears
![image](https://cloud.githubusercontent.com/assets/17527106/14766403/e284c67a-0a10-11e6-86a4-d390c7642a9a.png)

**Comment by alexazarh** [comment]
Duplicate of #626
