### ISSUE TITLE
When upgrading 7.0 EA to GA the qsconfig is running into an error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#677]
STR
Have a machine with 7.0 EA installed 
Upgrade to 7.0 GA 
Run Qsconfig 

BIR
an error occurs in the middle of the installation
![image](https://cloud.githubusercontent.com/assets/17527106/14940433/73e9ce14-0f7d-11e6-83ed-369df2145bee.png)

**The installation continues fine after the error is displayed...

Server Logs:

[logs.zip](https://github.com/QualiSystems/vCenterShell/files/243991/logs.zip)

**Comment by tornizanQ** [comment]
Related to story #650

**Comment by alexazarh** [comment]
The packages that failed the import are not our OOB packages. Its probably garbage from old stuff on your machine.
