### ISSUE TITLE
Move 'UpdateResourceLiveStatus' to setup

### ISSUE THREAD

**Issue by doppleware** [QualiSystems/vCenterShell#681]
Currently this is handled by the orchestration script (OK) but for some reason also in the driver itself (not OKAY)

**Comment by alexazarh** [comment]
@doppleware 
We cant remove the call to 'UpdateResourceLiveStatus' from power on/off because than the live status will not be updated if you run the power commands manually from a reservation.
However I can add calls to 'UpdateResourceLiveStatus' in setup & teardown?

**Comment by alexazarh** [comment]
We need to think about a better solution. It needs to be integration into the server in a better way...
