### ISSUE TITLE
Rerun a setup script on a reservation with some deployed apps that there VMs has no IP will return an unclear error

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#687]
STR
Have an reservation after setup with some deployed apps without an IP 
rerun the setup script 
Wait for timeout 

BIR
an unclear error 
![image](https://cloud.githubusercontent.com/assets/17527106/15037251/f4fab456-12a1-11e6-921c-556b4e7d4e08.png)

**Comment by alexazarh** [comment]
Its a known issue because we use scripts we cant change this
