### ISSUE TITLE
Support autoloading existing VM as deployed app

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#689]
user flow - (1) import the shell, (2) in the Inventory page create new resource and enter vcenter name and vm name, (3) press "start discovery" --> the resource should be created and be of type "deployed app" so it can use the vcenter commands.

(1) a shell for a deployed app, with attributes named vCenter Name and VM Name (full path). This shell should have an autoload command that finds the vcenter resource, run a command called GetUUID with the VM Name as input and returns a CloudProvider and VM_UUID so the resource becomes a deployed app.
*there are more attributes that are stored in the VM Properties, such as "IP Regex", auto events and maybe more (TBD), we need to make sure it's possible to return them  (talk with Shay)

(2) need to have a command called Get_UUID on the vCenter resource (not visible to the user)
--> need to check if that's possible to trigger a command on the vcenter from an autoload command outside of a reservation context (clicking "start discovery" on a resource which isn't a deployed app yet in the inventory)

need to validate that the family is Application

outcome:
- shell with a family and model, attribute associated it
- driver with GetInventory associated with the model
- resource template

assumptions:
- the vcenter shell is imported prior to using this pacakge

**Comment by tornizanQ** [comment]
[TestPlan](http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=153483)
