### ISSUE TITLE
VLAN ID Pools - Different pools create the same ID, but the GUI shows a connection error

### ISSUE THREAD

**Issue by TaiTheGreat** [QualiSystems/vCenterShell#690]
Have an environment with 2 apps and 2 VLANS. 
Make sure the VLANs have a different ID pool, and that at least one of them is set to Exclusive isolation level. 

Check the VLanItems table before to see nothing is there.

Reserve the environment. Connect the first VLAN. Connect the second VLAN. 

BIR if the "VLAN ID already exists" error appears and the connection fails, but when you check the VLanItems table both will appear under their respective pools.

**Comment by alonagetzler** [comment]
show a clear error to the user in this scenario, explaining that it isn't possible to show  same vlan ids in the same reservation, or at least that the problem is having same vlan ids.
