### ISSUE TITLE
The Deploy from link clone app form page order of fields has been changed

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#691]
![image](https://cloud.githubusercontent.com/assets/17527106/15096073/6508937a-14f1-11e6-9859-d7c7f47ba339.png)

**Comment by alonagetzler** [comment]
check what the order logic is, and if can be customized than the order should be - snapshot, vm, vcenter. if not possible please cancel

**Comment by alexazarh** [comment]
We cannot control this
