### ISSUE TITLE
Multiple NICs on the "Source/Target Nic" attribute on the CVC

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#704]
Preferred solution:
need the ability to have multiple source/target NICs on a a connector. the attribute should support a comma separated value and match according to order ("a,b,c" source nic and "x,y,z" target nic should result with a<->x,b<->y,c<->z connections)

any conflict that can arise here - two contradicting connections etc. - should result with an error and failure.

OR
if the above is too comlex than we will allo wto ave more than one vlan service with the same vlan id in the reservation by renaming the vlan in a correct way. IE: "Vlan 200_1", "Vlan 200_2"

**Comment by tornizanQ** [comment]
http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=153680

**Comment by tornizanQ** [comment]
A related bug in P2 is opened, 
https://github.com/QualiSystems/vCenterShell/issues/727
