### ISSUE TITLE
VLAN Default is visible and avalible for use for regular users

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#712]
STR 
Log in as a user with regular permission
Have an environment
open service side pane

BIR
The default VLAN is visible and available for use

**Comment by alonagetzler** [comment]
the new family should be called "Virtual Network - Administrative", should be marked as admin only and include only the "Default VLAN"  service model

**Comment by tornizanQ** [comment]
The "VLAN Default" service is still exist under "Virtual Network" service family and need to deleted.

**Comment by alexazarh** [comment]
Its because you tired it on an old DB.
The name of the service model changed to "P2P Default Vlan"  and the family also changed. So when you import the new package the old one wasn't delted

**Comment by alexazarh** [comment]
Bug verified by Roey Collignon
