### ISSUE TITLE
When Upgrading to 7.0GA from 6.3 with Huawei db some error appears when import packeges part is running

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#714]
Have a machine with 6.3GA on it with Huawei  db 
Upgrade the machine to 7.0GA

BIR
When qsconfig is on import packages step an error appears.

![2016-05-26 14_01_35-c__program files x86 _qualisystems_cloudshell_server_logs](https://cloud.githubusercontent.com/assets/17527106/15573066/256a886c-234d-11e6-8524-440537d55b83.png)

Logs

[LogsHuwa.zip](https://github.com/QualiSystems/vCenterShell/files/284062/LogsHuwa.zip)

**Comment by alexazarh** [comment]
The errors in the log indicate that its not related to our packages. If the error still persists than please open the bug the in tfs for App Scrum

**Comment by tornizanQ** [comment]
canceled, was related to windows permissions
