### ISSUE TITLE
ability to turn promiscuous mode on/off

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#722]
Promiscuous mode is a port group security policy definition. We need to support defining the default behavior (enable or disable promiscuous mode) when configuring a port group in the vCenter. This default behavior will be defined by the admin using the following attribute on the vCenter cloud provider resource:
Name: Promiscuous Mode
Type: Boolean
Default: True
Description: If enabled the port groups on the virtual switch will be configured to allow promiscuous mode.

This attribute should also appear in the vCenter shell template. More details about promiscuous mode can be found here - [https://kb.vmware.com/selfservice/microsites/search.do?language=en_US&cmd=displayKC&externalId=1004099](url)

![promiscuous](https://cloud.githubusercontent.com/assets/16175869/17480004/6d2b9cac-5d7e-11e6-9fd2-a607690c51ea.png)

**Comment by TaiTheGreat** [comment]
Tested:
- Off, on, migration.
Verified.

**Comment by Shnitselon** [comment]
documented in the customizing app deployment types topic (for vCenter) as:
Promiscuous Mode: If enabled, the port groups on the virtual switch will be configured to allow all incoming traffic.
