### ISSUE TITLE
A sorry page is appears when changing a connection vnics and trying to disconnect the CVC after a connection had been done

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#726]
STR
Have a reservation with an undeployed app and a vlan
attach the app and the vlan via CVC
Change the vnic attribute to 1,2 and save 
Connect the CVC
Change the vnics attribute to 3,4
Disconnect the CVC

BIR
A sorry page appears 

Logs:
[Logs1452.zip](https://github.com/QualiSystems/vCenterShell/files/300311/Logs1452.zip)

**Comment by razaba** [comment]
please move TFS

**Comment by tornizanQ** [comment]
Moved to TFS
