### ISSUE TITLE
Two undeployed apps  connecting via CVC when both of them requesting a specific 2 differen vnics will end in partial connection

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#727]
STR
Have a reservation with two apps linked together via CVC 
Open Connector Attribute side pane
Change the value of requested source to 1,2
Change the value of requested target to 3,4
Deploy both apps 

Bir 
The connection is Partially Connected
***Sometimes when trying to disconnect this connection, a Sorry page appears but this part is unstable...

![image](https://cloud.githubusercontent.com/assets/17527106/15821833/f638b666-2bfa-11e6-8c9f-807b61a2d4ee.png)

![image](https://cloud.githubusercontent.com/assets/17527106/15821811/cd485c70-2bfa-11e6-9cb7-38eefe8ff915.png)

Logs:
[Logs1524.zip](https://github.com/QualiSystems/vCenterShell/files/300347/Logs1524.zip)

**Comment by alexazarh** [comment]
Cannot reproduce
