### ISSUE TITLE
new method GetNumericRangeFromRange in the pool API

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#732]

**Comment by doppleware** [comment]
Example request:
{
    "type": "NextAvailableNumericRangeFromRange",
    "poolId": "Global",
    "reservationId": "ID",
    "ownerId": "{service_id}",
    "isolation": "Exclusive",
    "length": 5,
    "requestedRange": {
        "start": 4,
        "end": 4094
    }
}
