### ISSUE TITLE
Cleanup Static VM feature

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#767]
To do:
### - fix data model and autoload: 
- [x] 1. (1) driver name should be "vCenter Static VM Autoload", 
- [x] 2. (2) the description of the resource template should be "A generic shell for loading existing vCenter VMs to CloudShell inventory.", 
- [x] 3. (3) the description of the autoload part in the resource template should be "Fill in the inputs and click "start discovery" to load a vCenter VM into CloudShell Inventory as a static VM.", 
- [x] 4. (4) the attributes

>      
>       -  IP Regex
>       -  Refresh IP Timeout
>       -  Auto Power On
>      

 shouldn't be associated with the "vCenter Static VM" model, 
- [x] 6. (6) the family should be identical to the "Generic App Family" but not "locked by default" and named 
- [x] 7. "Generic Static VM"
- [x] 5. (5) in the data-model the association with "vCenter Static VM" model shouldn't include "UserInput" tags as it is irrelevant for such model type. 

### -----------------------------------------------------------------
- check if possible to add class for this type of response in Autoload (cloudshell shell core) and return object and not JSON
- validate that the driver requirements are in the correct version
- the outcome should be part of the vCenter shell
- document that this is shared by default, how to make it locked by default, how to use the sample code. update 7.1 EA documentation that this is in the community and 7.1 GA documentation that this is OOB with the vCenter shell.

Testing notes:
The main use case here is that the VM is a shared VM, used in multiple reservations at the same time. We should never allow delete such a VM from the vCenter via CloudShell. The OOB setup and teardown should ignore this VM - no automatic power on/off, no connectivity, no auto-delete. The connectivity of such VM isn't handled via CloudShell, it is usually connected to some management network and we shouldn't allow dragging connection between this to VLAN services and connecting/disconnecting them.

![Image of Yaktocat](https://pbs.twimg.com/profile_images/567285191169687553/7kg_TF4l.jpeg)

**FOR PV: Make sure that the cloudshell-shell-core is updated in PYPI and the version is 2.4.0 + and not 2.2-
@tornizanQ 

https://pypi.python.org/pypi/cloudshell-shell-core/2.3.1
**

**Comment by alonagetzler** [comment]
need to decide if that's a separate family or not? how does it fit the common use case of this being shared.

**Comment by alexazarh** [comment]
@alonagetzler Do we want to get the IP address of the static VM or not?
If we remove the "IP Regex", "Refresh IP Timeout" attributes than we will not be able get the ip address...

**Comment by alonagetzler** [comment]
@alexazarh let's remove the "IP Regex" and "Refresh IP Timeout" attributes, require the user to fill in the address (in the shell template) and validate that the address exists on this VM in vCenter as part of the Auoload

**Comment by GilGald** [comment]
take a look at _try_get_ip  in vm_autoload_driver

**Comment by alonagetzler** [comment]
@GilGald  & @alexazarh please note we should block connect/disconnect CVC to such static VM, user which creates a connection to static VM and clicks connect should get a message that connectivity is not supported for Static VMs.  Need to make sure that Setup (and Teardown) doesn't fail in case there is a static VM connected with CVC to something (resource/app), the connection just shouldn't be connected as part of the setup.

**Comment by tornizanQ** [comment]
(Test Plan)[http://team:8080/tfs/Quali-Collection/QualiSystems/_testmanagement#planId=125053&suiteId=153483]

**Comment by tornizanQ** [comment]
Need to add a check that  the user won't be able to create two static VMs linked to the same VM in the vCenter

**Comment by alonagetzler** [comment]
updates to the story following new feedback:
1. the family should be "Generic App Family", which is locked by default.
2. we shouldn't block connectivity. it should be possible to drag a CVC to the static VM and connect/disconnect it.
3. the package shouldn't be OOB, it should be a separate package than the vCenter Shell package and will be posted in the community. This deliverable should be passed by PV to the Release Manager (Yaron) which will post it in the community.

**Comment by GilGald** [comment]
**FOR PV: Make sure that the cloudshell-shell-core is updated in PYPI and the version is 2.4.0 + and not 2.2-
@tornizanQ 
**

**Comment by tornizanQ** [comment]
https://github.com/QualiSystems/vCenterShell/issues/773

**Comment by tornizanQ** [comment]
https://github.com/QualiSystems/vCenterShell/issues/778 
related bug
