### ISSUE TITLE
Online help update static VM

### ISSUE THREAD

**Issue by GilGald** [QualiSystems/vCenterShell#768]
document that this is shared by default, how to make it locked by default, how to use the sample code. update 7.1 EA documentation that this is in the community and 7.1 GA documentation that this is OOB with the vCenter shell.

**Comment by tornizanQ** [comment]
At the end, in 7.1GA, static vm will be OOB feature and not from package? and is it shared by default? or is it some old topic?

**Comment by alonagetzler** [comment]
no.. it won't be OOB but instead a separate package that will be posted in the community, and it will be locked by default (generic app family). see the latest comment in the story
