### ISSUE TITLE
Deploy from image does not work properly

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/vCenterShell#788]
Need to consider to change the way we execute the OVF tool exec.

According to Yaniv Kalsky the better way to execute the ovf tool is to changed the part that sends the command as a list of args to a single string. Sending it like this helped him, and in other cases with EMC (you can ask Omri). Example for the changes he made:

        args = self._get_args("\"" + ovf_tool_exe_path + "\"", image_params)
        logger.debug('opening ovf tool process with the params: {0}'.format(','.join(args)))
        args1 = " ".join(args)
        process = subprocess.Popen(args1, shell=True, stdin=subprocess.PIPE, stdout=subprocess.PIPE,
                                   stderr=subprocess.PIPE)

of course this is just a quick&dirty change.
but once the command is sent like this, you'll get an error after the deploy is done, so i didn't continue to check from where it comes (the vm itself is deployed..)

**Comment by alexazarh** [comment]
Cannot reproduce bug. Waiting to get more infro from Yaniv

**Comment by tornizanQ** [comment]
As it seems know this feature "VCENTER IMAGE ARGUMENT" is not working correctly, If I'm using this command through OVF Tool directly it's works fine

**Comment by alexazarh** [comment]
I was able to resolve this by removing the quotes completely like this:
![image](https://cloud.githubusercontent.com/assets/6730546/18504131/60bcba34-7a69-11e6-80a4-35ed0765e9f4.png)

This is actually a bug in the description. Will update the description and remove the quotes from the example in the description.
