### ISSUE TITLE
Deploy a VM on a vCenter and get its basic information back to CloudShell

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#8]
As a user I want to deploy a VM from a specific template I input and view the VM in CloudShell

flow:
1. drag a "deploy vm" service
2. input a template (string)
3. click "deploy"
4. a resource is created with the following attributes - UUID and vCenter

note: the modeling of the resources in CloudShell is temporary
the VM should be powered On once deployed

**Comment by alexazarh** [comment]
UUID is currently set as the resource address. Is that ok or we need it as an attribute?

**Comment by doppleware** [comment]
Lets use an attribute, that was just for the original example.
Thanks!
