### ISSUE TITLE
In vCenter cloudprovider resource discovery Cluster attribute documentation and help changes, from ticket #28601

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#806]
Need to add a sample of how to insert the value (or change the behavior to be more elegant) .

![image](https://cloud.githubusercontent.com/assets/17527106/18900897/b9ff6dea-854e-11e6-8999-1fb66efaf646.png)

as for now to enter a direct storage youll need to enter its cluster first:

clustername/10.115.136.120 

and if the the storage is sitting by itself you'll need to enter the IP twice

10.115.136.120/10.115.136.120 

From ticket:#28601
https://qualisystemscom.zendesk.com/agent/tickets/28601

**Comment by TomerAdmon** [comment]
We will go with changing the description of the "VM Storage" attribute.

"The vCenter storage in which the VMs will be created. The storage can be either a datastore or a datastore cluster. For example: datastore1
(For using specific datastore inside a cluster, use the cluster name and the datastore name For Example: clustername/storage1)"

@Shnitselon  - Please review and update documentation

**Comment by Shnitselon** [comment]
Great description. Some minor edits (in bold) to the note in brackets:
**To use a** specific datastore inside a cluster, **specify** the cluster name and the datastore name For Example: clustername/storage1

**Comment by Shnitselon** [comment]
+ "...the datastore name**.** For **e**xample: clustername/storage1."

**Comment by TomerAdmon** [comment]
cool, we will go with that:
"The vCenter storage in which the VMs will be created. The storage can be either a datastore or a datastore cluster. For example: datastore1
(To use a specific datastore inside a cluster, specify the cluster name and the datastore name. For example: clustername/datastore1)"

**Comment by kalsky** [comment]
Hi @tornizanQ 
the ticket was about the VM Cluster attribute..
maybe it's relevant to this attribute as well, but the ticket talked about link-cloning to a specific host, in which case you'll need to specify the clustername/host in the VM Cluster attribute.
