### ISSUE TITLE
Do performance testing for the latest vCenter release

### ISSUE THREAD

**Issue by alexazarh** [QualiSystems/vCenterShell#818]
We need to understand the implications of the change to the connection object.
Sync with Yoav to use his environment for the perf testing

**Comment by tornizanQ** [comment]
Number of apps vs time to deploy via setup
**Old ver**
1 app 2 min          
10 app 6.5 min
30 app 15 min

**New ver**
1 app 2.1 min
10 app 7.5 min
30 app 15.25 min
