### ISSUE TITLE
Ticket #29467, Logs throws unclear error from logs ''str' object has no attribute 'message''

### ISSUE THREAD

**Issue by tornizanQ** [QualiSystems/vCenterShell#834]
STR
1) Have an environment with vCenter App 
2) Open RM
3) Change the password of the vCenter cloud provider to an unauthorized password and run Activate. 
4) Reserve the environment 
5) The app will fail to deploy

BIR
The error in the activity feed is not clear: 
'Error: AttributeError
Description: 'str' object has no attribute 'message'
Parameters:'

Logs:

[VMware_vCenter--18-Jan-2017--14-45-05.zip](https://github.com/QualiSystems/vCenterShell/files/713917/VMware_vCenter--18-Jan-2017--14-45-05.zip)

Solution according the Gil
![image](https://cloud.githubusercontent.com/assets/17527106/22064885/3ad6cde0-dd8e-11e6-92d3-1e2a87bb39e0.png)

**Comment by alexazarh** [comment]
please make sure to add a unit test for this bug
