### ISSUE TITLE
error messages from cloudshell_api.py calls appear in user unfriendly format

### ISSUE THREAD

**Issue by nahumtimerman** [QualiSystems/vCenterShell#88]
I ran VM deployment command. as part of the run, "ExecuteDeployAppCommand" was called and returned an error that script failed.

Error output to portal included a messy xml for error message with many escaped characters: 
&#xD;&#xA;&#xD;&#xA;

full message here:
Deploy App ended with status Failed with error: Error deploying app VM Deployment. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns="http://schemas.qualisystems.com/ResourceManagement/ApiCommandResult.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><ErrorCode>0</ErrorCode><ResponseInfo xsi:type="CommandExecutionFailedResultInfo" ErrorName="Script runner exited with exit code: 1" ErrorDescription="Traceback (most recent call last):&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA; exec code in run_globals&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\b1b5d5c8-db52-4441-b042-22fd69da1a42\Deploy.zip\__main__.py&quot;, line 11, in &lt;module&gt;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\b1b5d5c8-db52-4441-b042-22fd69da1a42\Deploy.zip\__main__.py&quot;, line 8, in main&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\b1b5d5c8-db52-4441-b042-22fd69da1a42\Deploy.zip\driver.py&quot;, line 27, in execute&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py&quot;, line 4923, in ExecuteCommand&#xD;&#xA; raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;&#xA;qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.&#xD;&#xA;&#xD;&#xA;Error description: 07/Jan/2016 16:22:20 DEBUG Folder composed: './logs'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 16:22:20 DEBUG Folder composed: './logs'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 16:22:20 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 16:22:20 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 16:22:23 INFO Starting new HTTPS connection (1): 192.168.70.28&#xD;&#xA;&#xD;&#xA;07/Jan/2016 16:22:23 DEBUG &quot;GET //sdk/vimServiceVersions.xml HTTP/1.1&quot; 200 530&#xD;&#xA;&#xD;&#xA;DEBUG&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA;&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA;&#xD;&#xA; exec code in run_globals&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\f51feeac-59aa-4f17-80c9-2573e53418ac\Deploy From Template.zip\__main__.py&quot;, line 51, in &lt;module&gt;&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\f51feeac-59aa-4f17-80c9-2573e53418ac\Deploy From Template.zip\__main__.py&quot;, line 39, in main&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\f51feeac-59aa-4f17-80c9-2573e53418ac\Deploy From Template.zip\vCenterShell\command_executer.py&quot;, line 44, in deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\f51feeac-59aa-4f17-80c9-2573e53418ac\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 131, in execute_deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\f51feeac-59aa-4f17-80c9-2573e53418ac\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 49, in _deploy_from_template&#xD;&#xA;&#xD;&#xA;ValueError: Failed to find folder: QualiSB/Alex&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;"><ErrorParameters/></ResponseInfo></Response>

**Comment by alexazarh** [comment]
Please post here the full error you get

**Comment by nahumtimerman** [comment]
Deploy App ended with status Failed with error: Error deploying app VM Deployment. Error: <?xml version="1.0" encoding="utf-8"?><Response CommandName="ExecuteDeployAppCommand" Success="false" xmlns="http://schemas.qualisystems.com/ResourceManagement/ApiCommandResult.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema"><ErrorCode>0</ErrorCode><ResponseInfo xsi:type="CommandExecutionFailedResultInfo" ErrorName="Script runner exited with exit code: 1" ErrorDescription="Traceback (most recent call last):&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA; exec code in run_globals&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\d4b33d9b-1ad9-43fe-a0c9-79a62e11d661\Deploy.zip\__main__.py&quot;, line 11, in &lt;module&gt;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\d4b33d9b-1ad9-43fe-a0c9-79a62e11d661\Deploy.zip\__main__.py&quot;, line 8, in main&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\d4b33d9b-1ad9-43fe-a0c9-79a62e11d661\Deploy.zip\driver.py&quot;, line 27, in execute&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py&quot;, line 4923, in ExecuteCommand&#xD;&#xA; raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)&#xD;&#xA;qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.&#xD;&#xA;&#xD;&#xA;Error description: 07/Jan/2016 17:45:40 DEBUG Folder composed: './logs'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 17:45:40 DEBUG Folder composed: './logs'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 17:45:40 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 17:45:40 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'&#xD;&#xA;&#xD;&#xA;07/Jan/2016 17:45:40 INFO Starting new HTTPS connection (1): 192.168.42.1101&#xD;&#xA;&#xD;&#xA;07/Jan/2016 17:45:43 WARNING Connection Error: (HTTPSConnectionPool(host='192.168.42.1101', port=443): Max retries exceeded with url: //sdk/vimServiceVersions.xml (Caused by NewConnectionError('&lt;requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0306BFF0&gt;: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))):&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\590dddd8-2eb2-4d58-ba38-3d275b255760\Deploy From Template.zip\common\vcenter\vmomi_service.py&quot;, line 58, in connect&#xD;&#xA;&#xD;&#xA; si = self.pyvmomi_connect(host=address, user=user, pwd=password, port=port, sslContext=context)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 663, in SmartConnect&#xD;&#xA;&#xD;&#xA; sslContext)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 552, in __FindSupportedVersion&#xD;&#xA;&#xD;&#xA; sslContext)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 472, in __GetServiceVersionDescription&#xD;&#xA;&#xD;&#xA; tree = __GetElementTreeFromUrl(url, sslContext)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\pyVim\connect.py&quot;, line 438, in __GetElementTreeFromUrl&#xD;&#xA;&#xD;&#xA; sock = requests.get(url, verify=False)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\requests\api.py&quot;, line 67, in get&#xD;&#xA;&#xD;&#xA; return request('get', url, params=params, **kwargs)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\requests\api.py&quot;, line 53, in request&#xD;&#xA;&#xD;&#xA; return session.request(method=method, url=url, **kwargs)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\requests\sessions.py&quot;, line 468, in request&#xD;&#xA;&#xD;&#xA; resp = self.send(prep, **send_kwargs)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\requests\sessions.py&quot;, line 576, in send&#xD;&#xA;&#xD;&#xA; r = adapter.send(request, **kwargs)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\site-packages\requests\adapters.py&quot;, line 437, in send&#xD;&#xA;&#xD;&#xA; raise ConnectionError(e, request=request)&#xD;&#xA;&#xD;&#xA;ConnectionError: HTTPSConnectionPool(host='192.168.42.1101', port=443): Max retries exceeded with url: //sdk/vimServiceVersions.xml (Caused by NewConnectionError('&lt;requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x0306BFF0&gt;: Failed to establish a new connection: [Errno 11004] getaddrinfo failed',))&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;DEBUG&#xD;&#xA;&#xD;&#xA;Traceback (most recent call last):&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 162, in _run_module_as_main&#xD;&#xA;&#xD;&#xA; &quot;__main__&quot;, fname, loader, pkg_name)&#xD;&#xA;&#xD;&#xA; File &quot;C:\work\trunk\Drop\TestShell\ExecutionServer\python\2.7.10\lib\runpy.py&quot;, line 72, in _run_code&#xD;&#xA;&#xD;&#xA; exec code in run_globals&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\590dddd8-2eb2-4d58-ba38-3d275b255760\Deploy From Template.zip\__main__.py&quot;, line 51, in &lt;module&gt;&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\590dddd8-2eb2-4d58-ba38-3d275b255760\Deploy From Template.zip\__main__.py&quot;, line 39, in main&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\590dddd8-2eb2-4d58-ba38-3d275b255760\Deploy From Template.zip\vCenterShell\command_executer.py&quot;, line 44, in deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\590dddd8-2eb2-4d58-ba38-3d275b255760\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 131, in execute_deploy_from_template&#xD;&#xA;&#xD;&#xA; File &quot;C:\Users\nahum-t\AppData\Local\Temp\590dddd8-2eb2-4d58-ba38-3d275b255760\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py&quot;, line 49, in _deploy_from_template&#xD;&#xA;&#xD;&#xA;ValueError: si must be init as ServiceInstance&#xD;&#xA;&#xD;&#xA;&#xD;&#xA;"><ErrorParameters/></ResponseInfo></Response>

**Comment by nahumtimerman** [comment]
text gets cut when too long, so attached

[unfriendly error message.txt]
![2016-01-07 17_47_36-clipboard](https://cloud.githubusercontent.com/assets/7686953/12174679/c654e286-b566-11e5-80f4-cda113126412.png)
(https://github.com/QualiSystems/vCenterShell/files/81332/unfriendly.error.message.txt)

**Comment by nahumtimerman** [comment]
Assert.IsTrue failed. App Deploy Failed:

Traceback (most recent call last):

  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main

    "__main__", fname, loader, pkg_name)

  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 72, in _run_code

    exec code in run_globals

  File "C:\Users\nahum-t\AppData\Local\Temp\2b430bf8-74b7-4f99-add7-95c8c5d0193e\Deploy.zip\__main__.py", line 11, in <module>

  File "C:\Users\nahum-t\AppData\Local\Temp\2b430bf8-74b7-4f99-add7-95c8c5d0193e\Deploy.zip\__main__.py", line 8, in main

  File "C:\Users\nahum-t\AppData\Local\Temp\2b430bf8-74b7-4f99-add7-95c8c5d0193e\Deploy.zip\driver.py", line 27, in execute

  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\site-packages\qualipy\api\cloudshell_api.py", line 4923, in ExecuteCommand

    raise CloudShellAPIError(xo.ErrorCode, xo.Error, xmlres)

qualipy.api.cloudshell_api.CloudShellAPIError: CloudShell API error 104: Command execution failed with error: 'Script runner exited with exit code: 1'.



Error description: 14/Jan/2016 14:31:27 DEBUG Folder composed: './logs'



14/Jan/2016 14:31:27 DEBUG Folder composed: './logs'



14/Jan/2016 14:31:27 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'



14/Jan/2016 14:31:27 INFO Logging configured. [console:'DEBUG' file: 'DEBUG'] Log File: './logs/vCenter.log'



14/Jan/2016 14:31:27 INFO Starting new HTTPS connection (1): 192.168.42.105



14/Jan/2016 14:31:27 DEBUG "GET //sdk/vimServiceVersions.xml HTTP/1.1" 200 430



DEBUG



Traceback (most recent call last):



  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 162, in _run_module_as_main



    "__main__", fname, loader, pkg_name)



  File "C:\work\trunk\Testing\ShellsTesting\vCenterTesting\bin\Debug\ExecutionServerForTesting\python\2.7.10\lib\runpy.py", line 72, in _run_code



    exec code in run_globals



  File "C:\Users\nahum-t\AppData\Local\Temp\f2fa12dc-7e67-4dc2-8e00-92d36ef306dd\Deploy From Template.zip\__main__.py", line 51, in <module>



  File "C:\Users\nahum-t\AppData\Local\Temp\f2fa12dc-7e67-4dc2-8e00-92d36ef306dd\Deploy From Template.zip\__main__.py", line 39, in main



  File "C:\Users\nahum-t\AppData\Local\Temp\f2fa12dc-7e67-4dc2-8e00-92d36ef306dd\Deploy From Template.zip\vCenterShell\command_executer.py", line 44, in deploy_from_template



  File "C:\Users\nahum-t\AppData\Local\Temp\f2fa12dc-7e67-4dc2-8e00-92d36ef306dd\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py", line 131, in execute_deploy_from_template



  File "C:\Users\nahum-t\AppData\Local\Temp\f2fa12dc-7e67-4dc2-8e00-92d36ef306dd\Deploy From Template.zip\vCenterShell\commands\deploy_vm.py", line 49, in _deploy_from_template



ValueError: Failed to find folder: QualiSB/Alex
