### ISSUE TITLE
Add Shutdown type attribute to the vCenter to support both Hard and Soft Shutdown

### ISSUE THREAD

**Issue by alonagetzler** [QualiSystems/vCenterShell#92]
As an administrator I want to define the Shutdown method for the VMs deployed on the vCenter

Add an attribute called "Shutdown Method". The default value should be "Hard Shutdown".
The description of this input should be: "The value of this attribute will defined the Shutdown method for the Power Off command. Options are "Hard Shutdown", which will immediately shutdown the VM with the risk of data lost or "Soft Shutdown" which will gracefully shutdown the VM".

**Comment by doppleware** [comment]
This may already be fixed, can you verify?
